export type FlowKind = 'paid'|'commitment'|'purchase'|'guarantee'|'incentive';
export type FinancingFlow = {from:number;to:number;kind:FlowKind;label:string;date:string;note:string;url:string};
export type FinancingLoop = {id:string;title:string;nodes:string[];tickers:string[];flows:FinancingFlow[];boundary:string};
const amazon='https://www.sec.gov/Archives/edgar/data/1018724/000101872426000026/amzn-20260630.htm';
const nvCloud='https://www.sec.gov/Archives/edgar/data/1045810/000104581026000075/nvda-20260726.htm';
const msAnthropic='https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/';
export const financingAsOf='5 October 2026';
export const financingLoops:FinancingLoop[]=[
 {id:'amazon-openai',title:'Amazon × OpenAI',nodes:['Amazon / AWS','OpenAI'],tickers:['AMZN'],flows:[
 {from:0,to:1,kind:'paid',label:'$50B equity investment paid',date:'Q1–after June 2026 · disclosed 30 Jul',note:'All installments completed by the Q2 filing; final payment day is unspecified.',url:amazon},
 {from:1,to:0,kind:'purchase',label:'$100B incremental AWS contract · 8 years',date:'27 Feb 2026 · future consumption',note:'Additional to an earlier $38B contract. Spending schedule and financing attribution are undisclosed.',url:'https://openai.com/index/amazon-partnership/'}],boundary:'Funding and cloud purchases form a commercial loop. The investment is not evidence that all contract revenue depends on that funding.'},
 {id:'amazon-anthropic',title:'Amazon × Anthropic',nodes:['Amazon / AWS','Anthropic'],tickers:['AMZN'],flows:[
 {from:0,to:1,kind:'paid',label:'$18B cumulative investment paid',date:'Paid through 30 Jun 2026',note:'$18B paid cumulatively; remaining $15B is conditional and is excluded from the paid-only model.',url:amazon},
 {from:1,to:0,kind:'purchase',label:'>$100B incremental AWS contract · 10 years',date:'20 Apr 2026 · delivery milestones apply',note:'Existing commitments are excluded from this incremental amount.',url:'https://www.anthropic.com/news/anthropic-amazon-compute'},
 {from:0,to:1,kind:'commitment',label:'$15B remaining contingent facility',date:'As of 30 Jun 2026',note:'Draws depend on delivery milestones; excluded from completed funding.',url:amazon}],boundary:'Paid capital and future chip-dependent obligations have different timing. The $15B facility is not another completed payment.'},
 {id:'nvidia-coreweave',title:'NVIDIA × CoreWeave',nodes:['NVIDIA','CoreWeave'],tickers:['NVDA'],flows:[
 {from:0,to:1,kind:'paid',label:'$2B equity investment closed',date:'23 Jan 2026',note:'Cash investment in CoreWeave Class A shares.',url:'https://www.sec.gov/Archives/edgar/data/1769628/000176962826000044/crwv-20260123.htm'},
 {from:1,to:0,kind:'purchase',label:'NVIDIA hardware purchases · $ undisclosed',date:'AI factory buildout through 2030',note:'The portion purchased with this equity cannot be traced from public disclosures.',url:'https://nvidianews.nvidia.com/news/nvidia-and-coreweave-strengthen-collaboration-to-accelerate-buildout-of-ai-factories'},
 {from:0,to:1,kind:'guarantee',label:'$6.3B initial capacity backstop',date:'9 Sep 2025 → 13 Apr 2032',note:'NVIDIA may purchase residual unsold compute; availability, delivery and termination conditions apply. This is cloud service demand, not a second GPU order.',url:'https://www.sec.gov/Archives/edgar/data/1769628/000176962825000047/crwv-20250909.htm'}],boundary:'Do not add the $6.3B to NVIDIA’s aggregate $36B backstops: overlap has not been reconciled.'},
 {id:'nvidia-openai',title:'NVIDIA → OpenAI → cloud providers',nodes:['NVIDIA','OpenAI','Cloud providers'],tickers:['NVDA','MSFT','AMZN','ORCL'],flows:[
 {from:0,to:1,kind:'commitment',label:'$30B round participation',date:'27 Feb / 31 Mar 2026',note:'OpenAI closed a round of committed capital; NVIDIA-specific cash payment timing is unverified. The older September 2025 $100B letter of intent is not added.',url:'https://openai.com/index/accelerating-the-next-phase-ai/'},
 {from:1,to:2,kind:'purchase',label:'Cloud contracts / compute purchases',date:'2025–2026 contracts · multi-year delivery',note:'Azure $250B incremental, AWS $100B incremental and CoreWeave $22.4B aggregate are separate contracts. Do not sum these as NVIDIA sales.',url:'https://www.coreweave.com/news/coreweave-expands-agreement-with-openai-by-up-to-6-5b'},
 {from:2,to:0,kind:'purchase',label:'GPU procurement · financed portion unknown',date:'Deployment timing varies',note:'Cloud procurement also includes non-NVIDIA hardware, facilities and power. No disclosed $30B-to-GPU cash tracing.',url:'https://openai.com/index/scaling-ai-for-everyone/'}],boundary:'This is a routed financing loop, with two distinct revenue layers. Contract value is not recognized revenue or a GPU purchase amount.'},
 {id:'nvidia-anthropic',title:'NVIDIA → Anthropic → Microsoft Azure',nodes:['NVIDIA','Anthropic','Microsoft Azure'],tickers:['NVDA','MSFT'],flows:[
 {from:0,to:1,kind:'commitment',label:'Up to $10B NVIDIA investment',date:'18 Nov 2025 · payment unverified',note:'Microsoft separately announced up to $5B. Both are investment commitments, not verified cash in this dataset.',url:msAnthropic},
 {from:1,to:2,kind:'purchase',label:'$30B Azure compute commitment',date:'18 Nov 2025 · term undisclosed',note:'Plus infrastructure of up to 1GW; do not treat 1GW as an additional cash amount.',url:msAnthropic},
 {from:2,to:0,kind:'purchase',label:'NVIDIA systems · $ undisclosed',date:'Future deployments · timing undisclosed',note:'Azure purchases systems; NVIDIA’s share of the $30B services contract is unknown.',url:msAnthropic}],boundary:'Microsoft’s additional financing is in the ledger above; the triangle shows NVIDIA’s routed loop without converting Azure revenue into NVIDIA revenue.'},
 {id:'microsoft-openai',title:'Microsoft × OpenAI',nodes:['Microsoft / Azure','OpenAI'],tickers:['MSFT'],flows:[
 {from:0,to:1,kind:'paid',label:'$11.9B cumulative funding paid',date:'As of 30 Jun 2026',note:'Funded portion of a cumulative $13B commitment; this is not a new annual investment.',url:'https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm'},
 {from:1,to:0,kind:'purchase',label:'$250B incremental Azure contract',date:'28 Oct 2025 · duration undisclosed',note:'April 2026 amendment permits other clouds. OpenAI-to-Microsoft revenue share continues through 2030 with an undisclosed cap.',url:'https://blogs.microsoft.com/blog/2026/04/27/the-next-phase-of-the-microsoft-openai-partnership/'},
 {from:0,to:1,kind:'commitment',label:'$1.1B remaining funding commitment',date:'As of 30 Jun 2026',note:'$13B total less $11.9B funded. Azure contract duration is undisclosed, so no annual funding-to-purchases schedule is inferred.',url:'https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm'}],boundary:'FY2026 OpenAI commercial revenue including revenue share was $24.1B. Funding attribution is unknown; the $250B contract cannot be annualized without a term.'},
 {id:'nvidia-backstops',title:'NVIDIA × AI-cloud customers · aggregate',nodes:['NVIDIA','AI-cloud customers'],tickers:['NVDA'],flows:[
 {from:0,to:1,kind:'guarantee',label:'$36B residual-capacity obligations',date:'As of 26 Jul 2026 · typically 6 years',note:'Conditional compute purchases. Scheduled $6B FY2028, $8B FY2029, $7B FY2030, $6B FY2031, $9B thereafter; use by others or NVIDIA can reduce residual amounts.',url:nvCloud},
 {from:1,to:0,kind:'purchase',label:'Upfront NVIDIA hardware purchases',date:'Financed buildouts · amount undisclosed',note:'Filings describe customers purchasing hardware upfront. Aggregate related product revenue and counterparty names are undisclosed.',url:nvCloud}],boundary:'A capacity backstop supports buyers but is not equity funding. It may overlap CoreWeave and is never added to that order or equity scenarios.'},
 {id:'nvidia-sbe',title:'NVIDIA × SB Energy / OpenAI project',nodes:['NVIDIA','SB Energy / OpenAI project'],tickers:['NVDA'],flows:[
 {from:0,to:1,kind:'guarantee',label:'Up to $105B contingent tenant guarantee',date:'17 Aug 2026 · starts ~2028 / FY2029',note:'Initial 4.25GW project; up to 20-year term, conditional readiness and tenant defaults, with OpenAI indemnity. Maximum notional is not expected loss. Separate planned $1.5B equity is not treated as paid.',url:'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000069/nvda-20260817.htm'},
 {from:1,to:0,kind:'purchase',label:'NVIDIA infrastructure · future orders unknown',date:'Earliest capacity readiness ~2028',note:'Management’s $150–200B revenue potential per generation is not booked revenue, orders or a present-year estimate.',url:'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000073/q2fy27cfocommentary.htm'}],boundary:'This combines a project’s counterparties for readability. NVIDIA guarantees tenant obligations to SB Energy; OpenAI pays rent, and project procurement may pass through other buyers. Excluded from present-year revenue stress.'},
 ...(['OpenAI','Meta'] as const).map((customer,i):FinancingLoop=>({id:`amd-${customer.toLowerCase()}`,title:`AMD × ${customer}`,nodes:['AMD',customer],tickers:i?['AMD','META']:['AMD'],flows:[
 {from:0,to:1,kind:'incentive',label:'Up to 160M warrant shares · $0.01 exercise',date:i?'23 / 24 Feb 2026':'5 / 6 Oct 2025',note:'Equity incentive contingent on purchases and share-price milestones; not cash financing. Exercise price is not fair value.',url:i?'https://ir.amd.com/financial-information/sec-filings/content/0000002488-26-000045/amd-20260223.htm':'https://ir.amd.com/financial-information/sec-filings/content/0001193125-25-230895/d28189d8k.htm'},
 {from:1,to:0,kind:'purchase',label:'GPU deployment up to 6GW · $ undisclosed',date:'Multi-year · purchase milestones',note:'Full warrant vesting depends on purchase and other milestones. No supported dollar conversion is available.',url:'https://ir.amd.com/financial-information/sec-filings/content/0000002488-26-000123/amd-20260627.htm'}],boundary:'Purchase-linked equity incentives can affect economics and dilution. They do not establish financed or unreliable revenue.'}))
];
export const revenueReferences=[
 {company:'NVIDIA',value:302.970,period:'TTM ended 26 Jul 2026',formula:'FY2026 215.938 − H1 FY2026 90.805 + H1 FY2027 177.837',url:'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027'},
 {company:'AWS',value:148.404,period:'TTM ended 30 Jun 2026',formula:'Q3 2025 33.006 + Q4 35.579 + Q1 2026 37.587 + Q2 42.232',url:'https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx'},
 {company:'Microsoft',value:331.8,period:'FY2026 ended 30 Jun 2026',formula:'Reported annual company revenue; Azure revenue is not the denominator',url:'https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q4/press-release-webcast'},
 {company:'CoreWeave',value:7.590,period:'TTM ended 30 Jun 2026',formula:'FY2025 5.131 − H1 2025 2.194 + H1 2026 4.653',url:'https://investors.coreweave.com/news/news-details/2026/CoreWeave-Reports-Strong-Second-Quarter-2026-Results/default.aspx'}
];
export function financingSensitivity(returnShare:number,disruption:number,nvidiaYears:number){
 const nvidiaRevenue=302.970,awsRevenue=148.404;
 return [
 {name:'NVIDIA · confirmed equity only',basis:'$2B CoreWeave paid; funding-to-sales path untraced',pace:2/nvidiaYears*returnShare,revenue:nvidiaRevenue},
 {name:'NVIDIA · broader commitment scenario',basis:'$42B = CoreWeave 2 + OpenAI 30 + Anthropic up to 10; includes unverified payments',pace:42/nvidiaYears*returnShare,revenue:nvidiaRevenue},
 {name:'AWS · completed lab funding',basis:'$50B OpenAI / 8 years + $18B Anthropic / 10 years; excludes contingent $15B',pace:(50/8+18/10)*returnShare,revenue:awsRevenue}
 ].map(r=>({...r,stress:r.pace*disruption,percent:r.pace*disruption/r.revenue*100}));
}
