"use client";
import {useState} from 'react';
import {financingAsOf,financingLoops,financingSensitivity,revenueReferences} from './circular-financing-data';
import {financingSvg,flowColors} from './circular-financing-svg';
import {valueChainFinancials} from './value-chain-financials';
import './circular-financing.css';
import FinancingNetwork from './financing-network';
const status={paid:'Completed funding',commitment:'Funding commitment',purchase:'Commercial obligation / procurement',guarantee:'Conditional backstop / guarantee',incentive:'Equity incentive'};
export default function CircularFinancing(){
 const [selected,setSelected]=useState('amazon-openai');
 const [returnPct,setReturnPct]=useState(35),[disruptionPct,setDisruptionPct]=useState(25),[years,setYears]=useState(3);
 const loop=financingLoops.find(l=>l.id===selected)!;
 const rows=financingSensitivity(returnPct/100,disruptionPct/100,years);
 const financials:Record<string,{period:string;ebitdaMargin:number|null;fcfToEbitda:number|null;netDebtToEbitda:number|null;sourceRange:string}>=valueChainFinancials.companies;
 return <div className="cf" id="circular-financing">
 <div className="cf-head"><div><span className="eyebrow">CIRCULAR FINANCING · AS OF {financingAsOf.toUpperCase()}</span><h3>Who funds the buyer—and receives the spending?</h3><p>Compare financing amounts across companies, then explore each circular loop. Financing can support demand; public disclosures rarely trace that money into recognized supplier revenue.</p></div><a className="data-button secondary" href="/circular-financing-map.svg" target="_blank" rel="noreferrer">Open detailed loop diagrams ↗</a></div>
 <div className="cf-legend">{Object.entries(status).map(([kind,label])=><span key={kind}><i style={{background:flowColors[kind as keyof typeof flowColors]}}/>{label}</span>)}</div>
 <FinancingNetwork onLoop={setSelected}/>
 <div className="cf-loop-picker" aria-label="Financing loops">{financingLoops.map(l=><button key={l.id} aria-pressed={selected===l.id} onClick={()=>setSelected(l.id)}>{l.title}</button>)}</div>
 <div className="cf-map-head" id="financing-loop-detail"><h4>{loop.title}</h4><a href={`/financing-maps/${loop.id}.svg`} target="_blank" rel="noreferrer">Open this diagram ↗</a></div>
 <div className="cf-map" dangerouslySetInnerHTML={{__html:financingSvg(loop)}}/>
 <p className="cf-boundary">{loop.boundary}</p>
 <p className="cf-mobile-hint">Scroll the diagram horizontally. Full transaction details follow below.</p>
 <div className="cf-ledger" id="financing-ledger">{loop.flows.map((f,i)=><article key={i}><span className="cf-status" style={{color:flowColors[f.kind]}}>{status[f.kind]}</span><h4>{loop.nodes[f.from]} → {loop.nodes[f.to]}</h4><strong>{f.label}</strong><time>{f.date}</time><p>{f.note}</p><a href={f.url} target="_blank" rel="noreferrer">Dated source ↗</a></article>)}</div>
 <div className="cf-context"><h4>Connected financial data · selected participants</h4><div className="chain-table-wrap"><table><thead><tr><th>Company</th><th>Workbook period</th><th>EBITDA margin</th><th>FCF / EBITDA</th><th>Net debt / EBITDA</th><th>Source cells</th></tr></thead><tbody>{loop.tickers.map(t=>{const r=financials[t];return r?<tr key={t}><td>{t}</td><td>{r.period}</td><td>{r.ebitdaMargin===null?'Unavailable':`${r.ebitdaMargin.toFixed(1)}%`}</td><td>{r.fcfToEbitda===null?'Unavailable':`${(r.fcfToEbitda*100).toFixed(1)}%`}</td><td>{r.netDebtToEbitda===null?'Unavailable':`${r.netDebtToEbitda.toFixed(2)}×`}</td><td>{r.sourceRange}</td></tr>:null})}</tbody></table></div><p>Existing workbook ratios are consolidated company figures. Private labs and CoreWeave are absent; they are not assigned another company’s ratios. Revenue denominators below come from dated filings, separately from these workbook ratios.</p></div>
 <div className="cf-estimate"><span className="eyebrow">CONSERVATIVE SENSITIVITY · ASSUMPTIONS, NOT MEASURED REVENUE</span><h3>How much annual demand could depend on supplier funding?</h3><p>Estimate funding returned as purchases, spread it over time, then stress a fraction of that demand. These are illustrative future annual equivalents compared with the latest historical revenue—not a restatement of reported revenue, a loss forecast or an upper bound.</p>
 <div className="cf-controls"><label>Funding returned to supplier: {returnPct}%<input aria-label="Funding returned to supplier" type="range" min="0" max="100" step="5" value={returnPct} onChange={e=>setReturnPct(Number(e.target.value))}/></label><label>Dependent demand disrupted: {disruptionPct}%<input aria-label="Dependent demand disrupted" type="range" min="0" max="100" step="5" value={disruptionPct} onChange={e=>setDisruptionPct(Number(e.target.value))}/></label><label>NVIDIA funding deployment: {years} years<input aria-label="NVIDIA funding deployment years" type="range" min="1" max="8" value={years} onChange={e=>setYears(Number(e.target.value))}/></label></div>
 <div className="chain-table-wrap"><table><thead><tr><th>Scenario / financing basis</th><th>Funding-linked annual purchase equivalent</th><th>Stressed annual demand</th><th>Reference revenue</th><th>Stress / revenue</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><b>{r.name}</b><small>{r.basis}</small></td><td>${r.pace.toFixed(3)}B</td><td>${r.stress.toFixed(3)}B</td><td>${r.revenue.toFixed(3)}B</td><td><b>{r.percent.toFixed(3)}%</b></td></tr>)}</tbody></table></div>
 <p className="cf-formula">Formula: paid or scenario funding ÷ deployment years × {returnPct}% returned × {disruptionPct}% disrupted. AWS uses disclosed 8-year / 10-year contract terms as a flat spending assumption, not an investment amortization schedule. The same return assumption is applied for comparability. NVIDIA scenarios are alternatives; never add them.</p>
 <div className="cf-checks"><article><span>Measured customer exposure</span><strong>Microsoft · 7.26%</strong><p>$24.1B OpenAI commercial revenue including revenue share / $331.8B FY2026 company revenue. Funding attribution is unknown.</p><a href="https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm" target="_blank" rel="noreferrer">FY2026 10-K ↗</a></article><article><span>Future contract pace · assumption</span><strong>AWS · ≥15.16%</strong><p>($100B / 8 + $100B / 10) / $148.404B TTM revenue. This approximates the two incremental lab commitments; actual recognition is uneven. It does not measure funding dependence.</p></article><article><span>Contingent cash support · separate</span><strong>NVIDIA · {(36/6*disruptionPct/100/302.970*100).toFixed(2)}%</strong><p>$36B / 6 years × {disruptionPct}% residual use / $302.970B TTM revenue. A cash-obligation scale comparison, not lost GPU revenue. Do not add to equity scenarios.</p></article></div>
 <p className="cf-boundary">No supported percentage of “unreliable revenue” can be measured from these disclosures. Financed purchases can be valid revenue. Timing, outside capital, non-supplier spending, contract cancellations and counterparty performance matter. The $105B project guarantee, AMD warrants and undated $250B Azure contract are excluded from annual funding-linked estimates.</p>
 <details><summary>Revenue denominators, calculation audit and coverage limits</summary><p><a href="/financing-edge-ledger.csv" download>Download dated source ledger (CSV)</a></p>{revenueReferences.map(r=><p key={r.company}><a href={r.url} target="_blank" rel="noreferrer">{r.company}: ${r.value.toFixed(3)}B · {r.period}</a><br/>{r.formula} (USD billions).</p>)}<p>Coverage is selected disclosed AI loops, not all global AI financing. Equity, warrants, backstops and tenant guarantees cannot be added into one funding total. Unknown payment status is explicitly preserved. NVIDIA’s superseded $100B OpenAI LOI is not a second investment pool. Financial workbook: {valueChainFinancials.sheet}, extracted {valueChainFinancials.extractedAt}; periods are retained. Sources were reviewed through {financingAsOf}; no automatic live updating.</p></details>
 </div></div>
}
