"use client";
import {useState} from 'react';
import {summarizeNode} from './financing-node-summary';
import {financingLoops,type FlowKind} from './circular-financing-data';
import graph from '../data/circular-financing.json';
const companies=graph.nodes;
const cutoffLabel=new Date(graph.informationCutoff+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
const networkEdges=graph.flows.filter(f=>!['cancelled','superseded'].includes(f.status)&&!['disputed','superseded'].includes(f.reconciliation.status)).map(f=>({id:f.id,loop:f.loopId,from:f.from,to:f.to,amount:f.amount.value,amountBound:f.amount.bound,kind:f.kind as FlowKind,label:f.label,date:f.time.label,note:f.newsBrief,url:graph.sources.find(s=>s.id===f.sourceIds[0])!.url}));
const roleColors={hardware:'#7357a6',cloud:'#267c94',lab:'#c27632',project:'#65784b',platform:'#94607b'};
const modes:{kind:FlowKind;label:string;color:string}[]=[{kind:'paid',label:'Paid funding',color:'#7045b6'},{kind:'commitment',label:'Future funding',color:'#7045b6'},{kind:'guarantee',label:'Backstops & guarantees',color:'#a16a0a'},{kind:'purchase',label:'Purchase commitments',color:'#176ca4'},{kind:'incentive',label:'Warrants',color:'#aa4280'}];
export default function FinancingNetwork({onLoop}:{onLoop:(id:string)=>void}){
 const [kinds,setKinds]=useState<FlowKind[]>(['paid']),[focus,setFocus]=useState<string|null>(null),[edgeId,setEdgeId]=useState<string|null>(null);
 const visible=networkEdges.filter(e=>kinds.includes(e.kind)&&(!focus||e.from===focus||e.to===focus));
 const maxSummaryRows=Math.max(1,...companies.flatMap(c=>[summarizeNode(visible,c.id,'in').length,summarizeNode(visible,c.id,'out').length]));
 const nodeHeight=108+maxSummaryRows*20;
 const nodePitch=nodeHeight+80;
 const positioned=companies.filter(c=>visible.some(e=>e.from===c.id||e.to===c.id)).map(c=>({...c,y:110+companies.filter(n=>n.x===c.x&&visible.some(e=>e.from===n.id||e.to===n.id)).findIndex(n=>n.id===c.id)*nodePitch}));
 const canvasHeight=Math.max(2,...[50,850].map(x=>positioned.filter(c=>c.x===x).length))*nodePitch+150;
 const active=visible.find(e=>e.id===edgeId);
 const color='#65758a';
 const edgeColor=(kind:FlowKind)=>modes.find(m=>m.kind===kind)!.color;
 const geometry=(e:typeof networkEdges[number])=>{const a=positioned.find(c=>c.id===e.from)!,b=positioned.find(c=>c.id===e.to)!;const peers=visible.filter(n=>(n.from===e.from&&n.to===e.to)||(n.from===e.to&&n.to===e.from));const offset=(peers.findIndex(n=>n.id===e.id)-(peers.length-1)/2)*24;const reverse=a.x>b.x;return {a,b,reverse,x1:reverse?a.x:a.x+300,x2:reverse?b.x+300:b.x,y1:a.y+nodeHeight/2+offset,y2:b.y+nodeHeight/2+offset};};
 const connected=new Set(visible.flatMap(e=>[e.from,e.to]));
 const width=(amount:number|null)=>amount===null?2:Math.max(2,amount*.22);
 return <section className="fn" id="weighted-financing"><div className="cf-map-head"><div><h4>Amount-weighted company network</h4><p>Select one or more flow types, then a company or arrow to inspect its connections.</p></div>{focus&&<button className="data-button secondary" onClick={()=>{setFocus(null);setEdgeId(null)}}>Show all companies</button>}</div>
 <div className="fn-modes">{modes.map(m=><button key={m.kind} aria-pressed={kinds.includes(m.kind)} onClick={()=>{setKinds(current=>current.includes(m.kind)?current.filter(k=>k!==m.kind):[...current,m.kind]);setEdgeId(null)}}>{m.label}</button>)}</div>
 <div className="fn-role-legend">{Object.entries(roleColors).map(([role,c])=><span key={role}><i style={{background:c}}/>{({hardware:'Chip / systems supplier',cloud:'Cloud infrastructure',lab:'Frontier lab',project:'Project developer / tenant',platform:'Application platform'} as Record<string,string>)[role]}</span>)}</div>
 <div className="fn-scale"><b>Arrow width = disclosed USD amount</b><svg viewBox="0 0 430 65" aria-label="Width examples: 2, 10, 50 and 100 billion dollars">{[2,10,50,100].map((n,i)=><g key={n}><line x1={i*105+5} x2={i*105+85} y1="23" y2="23" stroke={color} strokeWidth={width(n)}/><text x={i*105+45} y="58" textAnchor="middle" fontSize="13">${n}B</text></g>)}</svg><small>Linear scale: 0.22 SVG units / $1B; minimum 2 units for visibility. Unknown dollar amounts use a dotted hairline. Contract terms and funding periods differ.</small></div>
 {visible.length===0&&<p>{kinds.length===0?'Select at least one flow type to display connections.':'No disclosed flows of the selected types for this company. Choose “Show all companies” to broaden the map.'}</p>}
 <div className="fn-canvas"><svg viewBox={`0 0 1200 ${canvasHeight}`} role="img" aria-label={`${modes.filter(m=>kinds.includes(m.kind)).map(m=>m.label).join(', ')||'No selected flows'} network as of ${cutoffLabel}. Companies colored by supply-chain role.`}>
 <defs>{visible.map(e=><marker key={e.id} id={`fn-arrow-${e.id}`} viewBox="0 0 10 10" refX="10" refY="5" markerWidth={Math.max(18,width(e.amount)*1.6)} markerHeight={Math.max(18,width(e.amount)*1.6)} markerUnits="userSpaceOnUse" orient="auto"><path d="M0 0L10 5L0 10Z" fill={edgeColor(e.kind)}/></marker>)}</defs>
 <text x="50" y="40" fontSize="18" fill="#203449">Suppliers / financiers</text><text x="850" y="40" fontSize="18" fill="#203449">Customers / recipients</text>
 {visible.map((e,i)=>{const {a,b,reverse,x1,x2,y1,y2}=geometry(e);const d=`M${x1},${y1} C${reverse?680:520},${y1} ${reverse?520:680},${y2} ${x2},${y2}`;const chosen=active?.id===e.id;return <g key={e.id} role="button" tabIndex={0} aria-label={`${a.name} to ${b.name}: ${e.label}; ${e.date}`} onClick={()=>setEdgeId(e.id)} onKeyDown={v=>{if(v.key==='Enter'||v.key===' '){v.preventDefault();setEdgeId(e.id)}}} style={{cursor:'pointer'}}><title>{`${e.label} · ${e.date}`}</title><path d={d} fill="none" stroke="transparent" strokeWidth={Math.max(20,width(e.amount)+10)}/><path d={d} fill="none" stroke={edgeColor(e.kind)} strokeWidth={width(e.amount)} strokeOpacity={active&&!chosen?0.22:0.75} strokeDasharray={e.amount===null?'3 6':e.kind==='commitment'||e.kind==='guarantee'?'10 6':undefined} markerEnd={`url(#fn-arrow-${e.id})`}/></g>})}
 {visible.map((e,i)=>{const {a,b,reverse,x1,x2,y1,y2}=geometry(e);const t=[.27,.5,.73][i%3],u=1-t;const lx=u*u*u*x1+3*u*u*t*(reverse?680:520)+3*u*t*t*(reverse?520:680)+t*t*t*x2,ly=u*u*u*y1+3*u*u*t*y1+3*u*t*t*y2+t*t*t*y2;return <g key={`label-${e.id}`} style={{pointerEvents:'none'}}><rect x={lx-58} y={ly-13} width="116" height="28" rx="6" fill="#f8fafc" fillOpacity=".95"/><text x={lx} y={ly+6} textAnchor="middle" fontSize="16" fill={edgeColor(e.kind)}>{e.amount===null?'$ undisclosed':`${e.amountBound==='lower_bound'?'>':e.amountBound==='upper_bound'?'≤':''}$${e.amount}B`}</text></g>})}
 {positioned.map(c=><g key={c.id} role="button" tabIndex={0} aria-label={`Focus ${c.name}`} onClick={()=>{setFocus(focus===c.id?null:c.id);setEdgeId(null)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setFocus(focus===c.id?null:c.id);setEdgeId(null)}}} opacity={connected.has(c.id)?1:.25} style={{cursor:'pointer'}}><title>{`${c.name}\nIN: ${visible.filter(e=>e.to===c.id).map(e=>e.label).join('; ')||'No visible flows'}\nOUT: ${visible.filter(e=>e.from===c.id).map(e=>e.label).join('; ')||'No visible flows'}`}</title><rect x={c.x} y={c.y} width="300" height={nodeHeight} rx="12" fill="#fff" stroke={roleColors[c.role as keyof typeof roleColors]} strokeWidth={focus===c.id?4:2}/><rect x={c.x} y={c.y} width="8" height={nodeHeight} rx="4" fill={roleColors[c.role as keyof typeof roleColors]}/><text x={c.x+22} y={c.y+37} fontSize="22" fill="#203449">{c.name}</text><text x={c.x+22} y={c.y+65} fontSize="13" fill={roleColors[c.role as keyof typeof roleColors]}>{c.label}</text><line x1={c.x+18} x2={c.x+282} y1={c.y+78} y2={c.y+78} stroke="#e1e7ed"/><text x={c.x+20} y={c.y+97} fontSize="12" fontWeight="bold" fill="#203449">IN ↓</text><text x={c.x+165} y={c.y+97} fontSize="12" fontWeight="bold" fill="#203449">OUT ↑</text>{(['in','out'] as const).map((direction,i)=>{const rows=summarizeNode(visible,c.id,direction);return <g key={direction}>{rows.length?rows.map((r,j)=><text key={r.kind} x={c.x+20+i*145} y={c.y+118+j*20} fontSize="12" fill={edgeColor(r.kind)}>{`${r.short}: ${r.value}`}</text>):<text x={c.x+20+i*145} y={c.y+118} fontSize="12" fill="#7890a2">No visible flows</text>}</g>})}</g>)}
 <text x="600" y={canvasHeight-20} textAnchor="middle" fontSize="14" fill="#587084">{`Information cutoff: ${cutoffLabel} · selected disclosed relationships · no aggregate funding total`}</text></svg></div>
 <p className="cf-formula">IN / OUT summaries use only currently visible connections, grouped by flow type. Amounts retain their different periods; they are not net cash flow. ≤ indicates an announced maximum; &gt; a disclosed lower bound; ? an unknown dollar amount. Support and warrants show counts rather than additive dollars because guarantees may overlap and warrants lack dollar valuations.</p>
 <p className="cf-mobile-hint">Scroll horizontally to inspect the network. Select an arrow for dated details.</p>
 {active?<aside className="fn-inspector fn-news-panel" role="dialog" aria-label="Related flow news" aria-live="polite" onKeyDown={e=>{if(e.key==='Escape')setEdgeId(null)}}><button className="fn-news-close" aria-label="Close flow news" onClick={()=>setEdgeId(null)}>×</button><span className="eyebrow">RELATED ANNOUNCEMENT / FILING BRIEF</span><strong>{companies.find(c=>c.id===active.from)!.name} → {companies.find(c=>c.id===active.to)!.name}: {active.label}</strong><p><b>Transaction / disclosure timing:</b> {active.date}</p><p>{active.note}</p><p><b>Flow type:</b> {modes.find(m=>m.kind===active.kind)!.label}. <b>Source:</b> {new URL(active.url).hostname}.</p><a href={active.url} target="_blank" rel="noreferrer">Read original announcement / filing ↗</a>{financingLoops.some(l=>l.id===active.loop)&&<a className="data-button secondary" href="#financing-loop-detail" onClick={()=>onLoop(active.loop)}>Explore this circular loop</a>}</aside>:<p className="cf-formula">Click an arrow to see amount, timing, status and source. Amounts are not normalized per year. Backstops are contingent support, not paid funding; $36B aggregate may overlap the $6.3B CoreWeave backstop. Warrants have no verified dollar fair value here. Multi-role companies are labeled with their relevant supply-chain activities.</p>}
 </section>
}
