// Generated by scripts/build-frontier-labs-snapshot.py. Do not edit manually.
export const frontierLabsSnapshot = {
  "metadata": {
    "source": "ai_companies_revenue_reports.csv",
    "asOf": "2026-09-24"
  },
  "labs": {
    "OpenAI": {
      "latest": ">$40B",
      "latestValue": 40.0,
      "latestDate": "13 Aug 2026",
      "latestType": "Annualized run rate",
      "latestConfidence": "Likely",
      "fy2025Revenue": "$13B",
      "end2025RunRate": "$21.4B",
      "growthFromEnd2025": 86.9,
      "series": [
        {
          "date": "2024-12-31",
          "label": "Dec-24",
          "value": 5.5,
          "type": "Annual recurring revenue (ARR)",
          "confidence": "Likely"
        },
        {
          "date": "2025-06-09",
          "label": "Jun-25",
          "value": 10.0,
          "type": "Annual recurring revenue (ARR)",
          "confidence": "Likely"
        },
        {
          "date": "2025-07-30",
          "label": "Jul-25",
          "value": 12.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2025-08-01",
          "label": "Aug-25",
          "value": 13.0,
          "type": "Annual recurring revenue (ARR)",
          "confidence": "Likely"
        },
        {
          "date": "2025-12-18",
          "label": "Dec-25",
          "value": 19.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2025-12-31",
          "label": "Dec-25",
          "value": 21.4,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2026-02-28",
          "label": "Feb-26",
          "value": 25.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2026-08-13",
          "label": "Aug-26",
          "value": 40.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        }
      ]
    },
    "Anthropic": {
      "latest": "$65B",
      "latestValue": 65.0,
      "latestDate": "31 Jul 2026",
      "latestType": "Annualized run rate",
      "latestConfidence": "Likely",
      "fy2025Revenue": "$4.5B",
      "end2025RunRate": "$9B",
      "growthFromEnd2025": 622.2,
      "series": [
        {
          "date": "2024-12-31",
          "label": "Dec-24",
          "value": 1.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2025-03-01",
          "label": "Mar-25",
          "value": 1.4,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2025-03-31",
          "label": "Mar-25",
          "value": 2.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2025-05-30",
          "label": "May-25",
          "value": 3.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2025-07-01",
          "label": "Jul-25",
          "value": 4.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2025-07-29",
          "label": "Jul-25",
          "value": 5.0,
          "type": "Annual recurring revenue (ARR)",
          "confidence": "Likely"
        },
        {
          "date": "2025-10-21",
          "label": "Oct-25",
          "value": 7.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2025-12-31",
          "label": "Dec-25",
          "value": 9.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2026-02-12",
          "label": "Feb-26",
          "value": 14.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2026-03-03",
          "label": "Mar-26",
          "value": 19.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2026-04-06",
          "label": "Apr-26",
          "value": 30.0,
          "type": "Annualized run rate",
          "confidence": "Confident"
        },
        {
          "date": "2026-05-15",
          "label": "May-26",
          "value": 47.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        },
        {
          "date": "2026-07-31",
          "label": "Jul-26",
          "value": 65.0,
          "type": "Annualized run rate",
          "confidence": "Likely"
        }
      ]
    }
  }
} as const;
