// Generated by scripts/build-infrastructure-snapshot.py. Do not edit manually.
export const infrastructureSnapshot = {
  "metadata": {
    "dataCenterAsOf": "2026-09-28",
    "chipAsOf": "2026-03-31",
    "coveredOwners": 5,
    "facilityCount": 93,
    "timelineRows": 545,
    "method": "Facility capacity uses the latest milestone on or before each quarter end. Conversion uses trailing-four-quarter compute CapEx divided by the change from 2025Q1 to 2026Q1."
  },
  "deploymentHistory": [
    {
      "quarter": "2023Q1",
      "itMw": 127.0,
      "additionMw": null,
      "allCoveredMw": 127.0,
      "h100e": 0.029
    },
    {
      "quarter": "2023Q2",
      "itMw": 214.0,
      "additionMw": 87.0,
      "allCoveredMw": 214.0,
      "h100e": 0.091
    },
    {
      "quarter": "2023Q3",
      "itMw": 340.0,
      "additionMw": 126.0,
      "allCoveredMw": 340.0,
      "h100e": 0.157
    },
    {
      "quarter": "2023Q4",
      "itMw": 340.0,
      "additionMw": 0.0,
      "allCoveredMw": 340.0,
      "h100e": 0.157
    },
    {
      "quarter": "2024Q1",
      "itMw": 408.0,
      "additionMw": 68.0,
      "allCoveredMw": 473.0,
      "h100e": 0.192
    },
    {
      "quarter": "2024Q2",
      "itMw": 753.0,
      "additionMw": 345.0,
      "allCoveredMw": 874.0,
      "h100e": 0.375
    },
    {
      "quarter": "2024Q3",
      "itMw": 1060.0,
      "additionMw": 307.0,
      "allCoveredMw": 1320.0,
      "h100e": 0.532
    },
    {
      "quarter": "2024Q4",
      "itMw": 1466.0,
      "additionMw": 406.0,
      "allCoveredMw": 1901.0,
      "h100e": 0.815
    },
    {
      "quarter": "2025Q1",
      "itMw": 1744.0,
      "additionMw": 278.0,
      "allCoveredMw": 2574.3,
      "h100e": 1.084
    },
    {
      "quarter": "2025Q2",
      "itMw": 2783.0,
      "additionMw": 1039.0,
      "allCoveredMw": 3705.4,
      "h100e": 2.005
    },
    {
      "quarter": "2025Q3",
      "itMw": 3311.0,
      "additionMw": 528.0,
      "allCoveredMw": 4426.3,
      "h100e": 2.657
    },
    {
      "quarter": "2025Q4",
      "itMw": 4621.0,
      "additionMw": 1310.0,
      "allCoveredMw": 6531.3,
      "h100e": 4.166
    },
    {
      "quarter": "2026Q1",
      "itMw": 5520.0,
      "additionMw": 899.0,
      "allCoveredMw": 8109.1,
      "h100e": 5.085
    },
    {
      "quarter": "2026Q2",
      "itMw": 8219.0,
      "additionMw": 2699.0,
      "allCoveredMw": 12068.3,
      "h100e": 8.31
    },
    {
      "quarter": "2026Q3*",
      "itMw": 9177.0,
      "additionMw": 958.0,
      "allCoveredMw": 13500.2,
      "h100e": 9.827
    }
  ],
  "deploymentByOwner": [
    {
      "company": "Microsoft",
      "sites": 7,
      "itMw": 1519.0,
      "h100e": 1.685,
      "capital": 57.5
    },
    {
      "company": "Alphabet",
      "sites": 20,
      "itMw": 3179.0,
      "h100e": 3.67,
      "capital": 120.4
    },
    {
      "company": "Meta",
      "sites": 16,
      "itMw": 2243.0,
      "h100e": 2.524,
      "capital": 85.0
    },
    {
      "company": "Amazon",
      "sites": 5,
      "itMw": 1743.0,
      "h100e": 1.354,
      "capital": 66.0
    },
    {
      "company": "Oracle",
      "sites": 6,
      "itMw": 493.0,
      "h100e": 0.594,
      "capital": 18.7
    }
  ],
  "computeHistory": [
    {
      "quarter": "2024Q1",
      "h100e": 1.498,
      "low": 1.111,
      "high": 2.018,
      "chipMw": 1356.3
    },
    {
      "quarter": "2024Q2",
      "h100e": 2.186,
      "low": 1.63,
      "high": 2.927,
      "chipMw": 1909.2
    },
    {
      "quarter": "2024Q3",
      "h100e": 3.051,
      "low": 2.295,
      "high": 4.057,
      "chipMw": 2579.9
    },
    {
      "quarter": "2024Q4",
      "h100e": 4.473,
      "low": 3.394,
      "high": 5.863,
      "chipMw": 3508.0
    },
    {
      "quarter": "2025Q1",
      "h100e": 6.411,
      "low": 4.943,
      "high": 8.287,
      "chipMw": 4560.8
    },
    {
      "quarter": "2025Q2",
      "h100e": 8.603,
      "low": 6.692,
      "high": 11.016,
      "chipMw": 5695.1
    },
    {
      "quarter": "2025Q3",
      "h100e": 11.29,
      "low": 8.826,
      "high": 14.342,
      "chipMw": 7072.4
    },
    {
      "quarter": "2025Q4",
      "h100e": 14.361,
      "low": 11.288,
      "high": 18.121,
      "chipMw": 8630.3
    },
    {
      "quarter": "2026Q1",
      "h100e": 13.34,
      "low": 10.434,
      "high": 16.862,
      "chipMw": 7715.7
    }
  ],
  "computeByOwner": [
    {
      "company": "Microsoft",
      "h100e": 3.323,
      "low": 2.558,
      "high": 4.305,
      "chipMw": 1955.2,
      "yoy": 95.8
    },
    {
      "company": "Alphabet",
      "h100e": 5.473,
      "low": 4.389,
      "high": 6.63,
      "chipMw": 3135.6,
      "yoy": 172.1
    },
    {
      "company": "Meta",
      "h100e": 1.95,
      "low": 1.51,
      "high": 2.522,
      "chipMw": 1135.8,
      "yoy": 77.4
    },
    {
      "company": "Amazon",
      "h100e": 1.499,
      "low": 1.161,
      "high": 1.934,
      "chipMw": 869.5,
      "yoy": 33.6
    },
    {
      "company": "Oracle",
      "h100e": 1.094,
      "low": 0.815,
      "high": 1.471,
      "chipMw": 619.5,
      "yoy": 128.1
    }
  ],
  "conversion": [
    {
      "company": "Microsoft",
      "computeCapex": 76.048,
      "h100eAdded": 1.626,
      "itMwAdded": 498.0,
      "capexPerMillionH100e": 46.8,
      "capexPerMw": 152.7
    },
    {
      "company": "Alphabet",
      "computeCapex": 66.06,
      "h100eAdded": 3.461,
      "itMwAdded": 845.0,
      "capexPerMillionH100e": 19.1,
      "capexPerMw": 78.2
    },
    {
      "company": "Meta",
      "computeCapex": 50.895,
      "h100eAdded": 0.851,
      "itMwAdded": 818.0,
      "capexPerMillionH100e": 59.8,
      "capexPerMw": 62.2
    },
    {
      "company": "Amazon",
      "computeCapex": 90.6,
      "h100eAdded": 0.377,
      "itMwAdded": 1371.0,
      "capexPerMillionH100e": 240.4,
      "capexPerMw": 66.1
    },
    {
      "company": "Oracle",
      "computeCapex": null,
      "h100eAdded": 0.615,
      "itMwAdded": 244.0,
      "capexPerMillionH100e": null,
      "capexPerMw": null
    }
  ],
  "usageBridge": {
    "year": 2025,
    "coveredLabH100e": 6.147,
    "coveredLabCount": 5,
    "assumedUtilization": 0.3,
    "trainingExamples": [
      {
        "lab": "OpenAI",
        "model": "GPT-4.5",
        "labH100e": 1743440.0,
        "trainingH100eYears": 20282.0,
        "fleetYearSharePct": 1.16
      },
      {
        "lab": "Meta Superintelligence Labs",
        "model": "Llama 4 Behemoth (preview)",
        "labH100e": 996228.0,
        "trainingH100eYears": 2767.0,
        "fleetYearSharePct": 0.28
      },
      {
        "lab": "SpaceXAI",
        "model": "Grok 4",
        "labH100e": 634793.0,
        "trainingH100eYears": 26687.0,
        "fleetYearSharePct": 4.2
      }
    ],
    "interpretation": "Illustrative H100e-years use Epoch's 1.979 PFLOP/s FP8 H100-equivalent definition and 30% effective utilization. Ownership, lab use, and training compute are distinct modeled datasets."
  }
} as const;
