// Generated by scripts/extract-roic.py. Do not edit inputs manually.
export const roicSnapshot = {
  "source": "Indexlist.xlsx",
  "sheet": "Hyperscaler Core Data Value",
  "sha256": "7bcb82c93af01c0fe8dd65123c1b5b9fbfff05755f8d012e5f36402aff99110e",
  "unit": "USD billions",
  "basis": "Cached Bloomberg BQ data; direct Bloomberg NOPAT and simplified core invested capital.",
  "companies": [
    {
      "ticker": "MSFT",
      "name": "Microsoft",
      "readiness": "ready",
      "readinessReason": "Direct Bloomberg NOPAT and core invested-capital fields available.",
      "financeLeasesExcludedFromDebt": true,
      "quarters": [
        {
          "period": "2022-12-31",
          "sourceRow": 3,
          "nopat": null,
          "cashAndShortTermInvestments": null,
          "totalDebt": null,
          "operatingLeaseLiabilities": null,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": null
        },
        {
          "period": "2023-03-31",
          "sourceRow": 4,
          "nopat": 18.039926255899086,
          "cashAndShortTermInvestments": 104.427,
          "totalDebt": 79.312,
          "operatingLeaseLiabilities": 14.639,
          "financeLeaseLiabilitiesCurrent": 1.153,
          "financeLeaseLiabilitiesLongTerm": 15.31,
          "shareholdersEquity": 194.683
        },
        {
          "period": "2023-06-30",
          "sourceRow": 5,
          "nopat": 19.69687281109718,
          "cashAndShortTermInvestments": 111.262,
          "totalDebt": 79.441,
          "operatingLeaseLiabilities": 15.137,
          "financeLeaseLiabilitiesCurrent": 1.197,
          "financeLeaseLiabilitiesLongTerm": 15.87,
          "shareholdersEquity": 206.223
        },
        {
          "period": "2023-09-30",
          "sourceRow": 6,
          "nopat": 21.973187399208328,
          "cashAndShortTermInvestments": 143.951,
          "totalDebt": 105.681,
          "operatingLeaseLiabilities": 16.025,
          "financeLeaseLiabilitiesCurrent": 1.577,
          "financeLeaseLiabilitiesLongTerm": 16.577,
          "shareholdersEquity": 220.714
        },
        {
          "period": "2023-12-31",
          "sourceRow": 7,
          "nopat": 22.287183895046372,
          "cashAndShortTermInvestments": 81.017,
          "totalDebt": 111.358,
          "operatingLeaseLiabilities": 16.942,
          "financeLeaseLiabilitiesCurrent": 1.691,
          "financeLeaseLiabilitiesLongTerm": 18.506,
          "shareholdersEquity": 238.268
        },
        {
          "period": "2024-03-31",
          "sourceRow": 8,
          "nopat": 22.64001043888203,
          "cashAndShortTermInvestments": 80.021,
          "totalDebt": 106.229,
          "operatingLeaseLiabilities": 17.882,
          "financeLeaseLiabilitiesCurrent": 1.869,
          "financeLeaseLiabilitiesLongTerm": 21.036,
          "shareholdersEquity": 253.152
        },
        {
          "period": "2024-06-30",
          "sourceRow": 9,
          "nopat": 22.581845871559633,
          "cashAndShortTermInvestments": 75.543,
          "totalDebt": 97.852,
          "operatingLeaseLiabilities": 19.077,
          "financeLeaseLiabilitiesCurrent": 2.349,
          "financeLeaseLiabilitiesLongTerm": 24.796,
          "shareholdersEquity": 268.477
        },
        {
          "period": "2024-09-30",
          "sourceRow": 10,
          "nopat": 24.897624103868644,
          "cashAndShortTermInvestments": 78.428,
          "totalDebt": 96.838,
          "operatingLeaseLiabilities": 20.37,
          "financeLeaseLiabilitiesCurrent": 2.504,
          "financeLeaseLiabilitiesLongTerm": 28.847,
          "shareholdersEquity": 287.723
        },
        {
          "period": "2024-12-31",
          "sourceRow": 11,
          "nopat": 25.98639618593564,
          "cashAndShortTermInvestments": 71.555,
          "totalDebt": 102.909,
          "operatingLeaseLiabilities": 21.862,
          "financeLeaseLiabilitiesCurrent": 2.673,
          "financeLeaseLiabilitiesLongTerm": 33.404,
          "shareholdersEquity": 302.695
        },
        {
          "period": "2025-03-31",
          "sourceRow": 12,
          "nopat": 26.336743474519555,
          "cashAndShortTermInvestments": 79.618,
          "totalDebt": 105.019,
          "operatingLeaseLiabilities": 22.924,
          "financeLeaseLiabilitiesCurrent": 2.889,
          "financeLeaseLiabilitiesLongTerm": 36.325,
          "shareholdersEquity": 321.891
        },
        {
          "period": "2025-06-30",
          "sourceRow": 13,
          "nopat": 28.658273822663723,
          "cashAndShortTermInvestments": 94.565,
          "totalDebt": 112.184,
          "operatingLeaseLiabilities": 22.861,
          "financeLeaseLiabilitiesCurrent": 3.172,
          "financeLeaseLiabilitiesLongTerm": 43.0,
          "shareholdersEquity": 343.479
        },
        {
          "period": "2025-09-30",
          "sourceRow": 14,
          "nopat": 30.707672283606893,
          "cashAndShortTermInvestments": 102.012,
          "totalDebt": 120.375,
          "operatingLeaseLiabilities": 22.733,
          "financeLeaseLiabilitiesCurrent": 3.435,
          "financeLeaseLiabilitiesLongTerm": 50.999,
          "shareholdersEquity": 363.076
        },
        {
          "period": "2025-12-31",
          "sourceRow": 15,
          "nopat": 30.509885793640922,
          "cashAndShortTermInvestments": 89.462,
          "totalDebt": 123.278,
          "operatingLeaseLiabilities": 22.865,
          "financeLeaseLiabilitiesCurrent": 3.738,
          "financeLeaseLiabilitiesLongTerm": 56.413,
          "shareholdersEquity": 390.875
        },
        {
          "period": "2026-03-31",
          "sourceRow": 16,
          "nopat": 31.01707280122013,
          "cashAndShortTermInvestments": 78.272,
          "totalDebt": 125.432,
          "operatingLeaseLiabilities": 22.238,
          "financeLeaseLiabilitiesCurrent": 4.063,
          "financeLeaseLiabilitiesLongTerm": 58.869,
          "shareholdersEquity": 414.367
        },
        {
          "period": "2026-06-30",
          "sourceRow": 17,
          "nopat": 32.969484823029944,
          "cashAndShortTermInvestments": 76.843,
          "totalDebt": 128.813,
          "operatingLeaseLiabilities": 21.925,
          "financeLeaseLiabilitiesCurrent": 4.29,
          "financeLeaseLiabilitiesLongTerm": 62.304,
          "shareholdersEquity": 442.387
        }
      ]
    },
    {
      "ticker": "GOOGL",
      "name": "Alphabet",
      "readiness": "ready",
      "readinessReason": "Direct Bloomberg NOPAT and core invested-capital fields available; long-term investments are not deducted.",
      "financeLeasesExcludedFromDebt": null,
      "quarters": [
        {
          "period": "2022-12-31",
          "sourceRow": 3,
          "nopat": null,
          "cashAndShortTermInvestments": null,
          "totalDebt": null,
          "operatingLeaseLiabilities": null,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": null
        },
        {
          "period": "2023-03-31",
          "sourceRow": 4,
          "nopat": 14.397866794836585,
          "cashAndShortTermInvestments": 115.102,
          "totalDebt": 29.121,
          "operatingLeaseLiabilities": 12.799,
          "financeLeaseLiabilitiesCurrent": 0.30794475138121546,
          "financeLeaseLiabilitiesLongTerm": 2.208,
          "shareholdersEquity": 260.894
        },
        {
          "period": "2023-06-30",
          "sourceRow": 5,
          "nopat": 18.313490572067753,
          "cashAndShortTermInvestments": 118.332,
          "totalDebt": 29.432,
          "operatingLeaseLiabilities": 15.409,
          "financeLeaseLiabilitiesCurrent": 0.318,
          "financeLeaseLiabilitiesLongTerm": 1.841,
          "shareholdersEquity": 267.141
        },
        {
          "period": "2023-09-30",
          "sourceRow": 6,
          "nopat": 19.824613247157615,
          "cashAndShortTermInvestments": 119.935,
          "totalDebt": 29.446,
          "operatingLeaseLiabilities": 15.265,
          "financeLeaseLiabilitiesCurrent": 0.4,
          "financeLeaseLiabilitiesLongTerm": 1.914,
          "shareholdersEquity": 273.202
        },
        {
          "period": "2023-12-31",
          "sourceRow": 7,
          "nopat": 20.081101056857285,
          "cashAndShortTermInvestments": 110.916,
          "totalDebt": 28.867,
          "operatingLeaseLiabilities": 15.251,
          "financeLeaseLiabilitiesCurrent": 0.363,
          "financeLeaseLiabilitiesLongTerm": 1.383,
          "shareholdersEquity": 283.379
        },
        {
          "period": "2024-03-31",
          "sourceRow": 8,
          "nopat": 21.286189793395724,
          "cashAndShortTermInvestments": 108.09,
          "totalDebt": 28.059,
          "operatingLeaseLiabilities": 14.831,
          "financeLeaseLiabilitiesCurrent": 0.6967773722627737,
          "financeLeaseLiabilitiesLongTerm": 1.672,
          "shareholdersEquity": 292.844
        },
        {
          "period": "2024-06-30",
          "sourceRow": 9,
          "nopat": 23.510982359986933,
          "cashAndShortTermInvestments": 100.725,
          "totalDebt": 27.801,
          "operatingLeaseLiabilities": 14.563,
          "financeLeaseLiabilitiesCurrent": 1.0305547445255474,
          "financeLeaseLiabilitiesLongTerm": 2.28,
          "shareholdersEquity": 300.753
        },
        {
          "period": "2024-09-30",
          "sourceRow": 10,
          "nopat": 23.65895480350722,
          "cashAndShortTermInvestments": 93.23,
          "totalDebt": 28.29,
          "operatingLeaseLiabilities": 14.625,
          "financeLeaseLiabilitiesCurrent": 1.368,
          "financeLeaseLiabilitiesLongTerm": 1.417,
          "shareholdersEquity": 314.119
        },
        {
          "period": "2024-12-31",
          "sourceRow": 11,
          "nopat": 25.489966566386503,
          "cashAndShortTermInvestments": 95.657,
          "totalDebt": 25.696,
          "operatingLeaseLiabilities": 14.578,
          "financeLeaseLiabilitiesCurrent": 0.235,
          "financeLeaseLiabilitiesLongTerm": 1.442,
          "shareholdersEquity": 325.084
        },
        {
          "period": "2025-03-31",
          "sourceRow": 12,
          "nopat": 25.296878125822587,
          "cashAndShortTermInvestments": 95.328,
          "totalDebt": 25.537,
          "operatingLeaseLiabilities": 14.551,
          "financeLeaseLiabilitiesCurrent": 0.1,
          "financeLeaseLiabilitiesLongTerm": 1.961,
          "shareholdersEquity": 345.267
        },
        {
          "period": "2025-06-30",
          "sourceRow": 13,
          "nopat": 25.9840602363481,
          "cashAndShortTermInvestments": 95.148,
          "totalDebt": 38.666,
          "operatingLeaseLiabilities": 14.959,
          "financeLeaseLiabilitiesCurrent": 0.1,
          "financeLeaseLiabilitiesLongTerm": 2.002,
          "shareholdersEquity": 362.916
        },
        {
          "period": "2025-09-30",
          "sourceRow": 14,
          "nopat": 24.832887262145633,
          "cashAndShortTermInvestments": 98.496,
          "totalDebt": 37.15,
          "operatingLeaseLiabilities": 15.205,
          "financeLeaseLiabilitiesCurrent": 0.338,
          "financeLeaseLiabilitiesLongTerm": 2.05,
          "shareholdersEquity": 386.867
        },
        {
          "period": "2025-12-31",
          "sourceRow": 15,
          "nopat": 31.651352864483474,
          "cashAndShortTermInvestments": 126.843,
          "totalDebt": 65.0,
          "operatingLeaseLiabilities": 15.954,
          "financeLeaseLiabilitiesCurrent": 0.441,
          "financeLeaseLiabilitiesLongTerm": 2.059,
          "shareholdersEquity": 415.265
        },
        {
          "period": "2026-03-31",
          "sourceRow": 16,
          "nopat": 31.532272359369916,
          "cashAndShortTermInvestments": 126.84,
          "totalDebt": 95.837,
          "operatingLeaseLiabilities": 16.161,
          "financeLeaseLiabilitiesCurrent": 0.177,
          "financeLeaseLiabilitiesLongTerm": 2.037,
          "shareholdersEquity": 478.746
        },
        {
          "period": "2026-06-30",
          "sourceRow": 17,
          "nopat": 30.468748358241395,
          "cashAndShortTermInvestments": 242.474,
          "totalDebt": 118.65,
          "operatingLeaseLiabilities": 18.037,
          "financeLeaseLiabilitiesCurrent": 0.449,
          "financeLeaseLiabilitiesLongTerm": 2.141,
          "shareholdersEquity": 640.48
        }
      ]
    },
    {
      "ticker": "AMZN",
      "name": "Amazon",
      "readiness": "ready",
      "readinessReason": "Direct Bloomberg NOPAT and core invested-capital fields available; long-term investments are not deducted.",
      "financeLeasesExcludedFromDebt": null,
      "quarters": [
        {
          "period": "2022-12-31",
          "sourceRow": 3,
          "nopat": null,
          "cashAndShortTermInvestments": null,
          "totalDebt": null,
          "operatingLeaseLiabilities": null,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": null
        },
        {
          "period": "2023-03-31",
          "sourceRow": 4,
          "nopat": 3.6762498179169705,
          "cashAndShortTermInvestments": 64.405,
          "totalDebt": 162.779,
          "operatingLeaseLiabilities": 71.248,
          "financeLeaseLiabilitiesCurrent": 11.676,
          "financeLeaseLiabilitiesLongTerm": 10.771,
          "shareholdersEquity": 154.526
        },
        {
          "period": "2023-06-30",
          "sourceRow": 5,
          "nopat": 6.855455771519239,
          "cashAndShortTermInvestments": 63.97,
          "totalDebt": 153.917,
          "operatingLeaseLiabilities": 73.37,
          "financeLeaseLiabilitiesCurrent": 3.024,
          "financeLeaseLiabilitiesLongTerm": 10.434,
          "shareholdersEquity": 168.602
        },
        {
          "period": "2023-09-30",
          "sourceRow": 6,
          "nopat": 9.067376158831733,
          "cashAndShortTermInvestments": 64.169,
          "totalDebt": 153.461,
          "operatingLeaseLiabilities": 73.902,
          "financeLeaseLiabilitiesCurrent": 2.385,
          "financeLeaseLiabilitiesLongTerm": 10.081,
          "shareholdersEquity": 182.973
        },
        {
          "period": "2023-12-31",
          "sourceRow": 7,
          "nopat": 10.253720298114862,
          "cashAndShortTermInvestments": 86.78,
          "totalDebt": 154.556,
          "operatingLeaseLiabilities": 75.639,
          "financeLeaseLiabilitiesCurrent": 2.032,
          "financeLeaseLiabilitiesLongTerm": 10.077,
          "shareholdersEquity": 201.875
        },
        {
          "period": "2024-03-31",
          "sourceRow": 8,
          "nopat": 12.395565556724241,
          "cashAndShortTermInvestments": 85.074,
          "totalDebt": 153.741,
          "operatingLeaseLiabilities": 76.019,
          "financeLeaseLiabilitiesCurrent": 1.626,
          "financeLeaseLiabilitiesLongTerm": 9.614,
          "shareholdersEquity": 216.661
        },
        {
          "period": "2024-06-30",
          "sourceRow": 9,
          "nopat": 12.978414627746801,
          "cashAndShortTermInvestments": 89.092,
          "totalDebt": 150.577,
          "operatingLeaseLiabilities": 77.432,
          "financeLeaseLiabilitiesCurrent": 1.439,
          "financeLeaseLiabilitiesLongTerm": 9.388,
          "shareholdersEquity": 236.447
        },
        {
          "period": "2024-09-30",
          "sourceRow": 10,
          "nopat": 14.795915617896545,
          "cashAndShortTermInvestments": 88.051,
          "totalDebt": 150.634,
          "operatingLeaseLiabilities": 79.677,
          "financeLeaseLiabilitiesCurrent": 1.393,
          "financeLeaseLiabilitiesLongTerm": 9.426,
          "shareholdersEquity": 259.151
        },
        {
          "period": "2024-12-31",
          "sourceRow": 11,
          "nopat": 18.977220099333305,
          "cashAndShortTermInvestments": 101.202,
          "totalDebt": 147.838,
          "operatingLeaseLiabilities": 79.596,
          "financeLeaseLiabilitiesCurrent": 1.375,
          "financeLeaseLiabilitiesLongTerm": 9.227,
          "shareholdersEquity": 285.97
        },
        {
          "period": "2025-03-31",
          "sourceRow": 12,
          "nopat": 14.540601918907699,
          "cashAndShortTermInvestments": 94.565,
          "totalDebt": 150.502,
          "operatingLeaseLiabilities": 81.731,
          "financeLeaseLiabilitiesCurrent": 1.359,
          "financeLeaseLiabilitiesLongTerm": 9.024,
          "shareholdersEquity": 305.867
        },
        {
          "period": "2025-06-30",
          "sourceRow": 13,
          "nopat": 16.6944792635566,
          "cashAndShortTermInvestments": 93.18,
          "totalDebt": 151.917,
          "operatingLeaseLiabilities": 84.991,
          "financeLeaseLiabilitiesCurrent": 1.376,
          "financeLeaseLiabilitiesLongTerm": 9.827,
          "shareholdersEquity": 333.775
        },
        {
          "period": "2025-09-30",
          "sourceRow": 14,
          "nopat": 13.075445864394746,
          "cashAndShortTermInvestments": 94.197,
          "totalDebt": 152.737,
          "operatingLeaseLiabilities": 86.233,
          "financeLeaseLiabilitiesCurrent": 1.448,
          "financeLeaseLiabilitiesLongTerm": 10.317,
          "shareholdersEquity": 369.631
        },
        {
          "period": "2025-12-31",
          "sourceRow": 15,
          "nopat": 19.866653185491447,
          "cashAndShortTermInvestments": 123.029,
          "totalDebt": 169.934,
          "operatingLeaseLiabilities": 89.252,
          "financeLeaseLiabilitiesCurrent": 1.544,
          "financeLeaseLiabilitiesLongTerm": 10.742,
          "shareholdersEquity": 411.065
        },
        {
          "period": "2026-03-31",
          "sourceRow": 16,
          "nopat": 17.36627721929064,
          "cashAndShortTermInvestments": 143.089,
          "totalDebt": 226.848,
          "operatingLeaseLiabilities": 91.617,
          "financeLeaseLiabilitiesCurrent": 1.578,
          "financeLeaseLiabilitiesLongTerm": 11.747,
          "shareholdersEquity": 441.914
        },
        {
          "period": "2026-06-30",
          "sourceRow": 17,
          "nopat": 19.22750113418818,
          "cashAndShortTermInvestments": 122.988,
          "totalDebt": 241.995,
          "operatingLeaseLiabilities": 96.32,
          "financeLeaseLiabilitiesCurrent": 1.688,
          "financeLeaseLiabilitiesLongTerm": 11.763,
          "shareholdersEquity": 551.62
        }
      ]
    },
    {
      "ticker": "META",
      "name": "Meta",
      "readiness": "ready",
      "readinessReason": "Direct Bloomberg NOPAT and core invested-capital fields available.",
      "financeLeasesExcludedFromDebt": null,
      "quarters": [
        {
          "period": "2022-12-31",
          "sourceRow": 3,
          "nopat": null,
          "cashAndShortTermInvestments": null,
          "totalDebt": null,
          "operatingLeaseLiabilities": null,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": null
        },
        {
          "period": "2023-03-31",
          "sourceRow": 4,
          "nopat": 5.64649555221021,
          "cashAndShortTermInvestments": 37.439,
          "totalDebt": 28.262,
          "operatingLeaseLiabilities": 17.65,
          "financeLeaseLiabilitiesCurrent": 0.114,
          "financeLeaseLiabilitiesLongTerm": 0.573,
          "shareholdersEquity": 124.795
        },
        {
          "period": "2023-06-30",
          "sourceRow": 5,
          "nopat": 7.870966964381793,
          "cashAndShortTermInvestments": 53.446,
          "totalDebt": 36.978,
          "operatingLeaseLiabilities": 17.836,
          "financeLeaseLiabilitiesCurrent": 0.181,
          "financeLeaseLiabilitiesLongTerm": 0.579,
          "shareholdersEquity": 134.033
        },
        {
          "period": "2023-09-30",
          "sourceRow": 6,
          "nopat": 11.358279885877318,
          "cashAndShortTermInvestments": 61.123,
          "totalDebt": 36.876,
          "operatingLeaseLiabilities": 17.834,
          "financeLeaseLiabilitiesCurrent": 0.085,
          "financeLeaseLiabilitiesLongTerm": 0.574,
          "shareholdersEquity": 142.873
        },
        {
          "period": "2023-12-31",
          "sourceRow": 7,
          "nopat": 13.663405997144217,
          "cashAndShortTermInvestments": 65.403,
          "totalDebt": 37.924,
          "operatingLeaseLiabilities": 18.849,
          "financeLeaseLiabilitiesCurrent": 0.09,
          "financeLeaseLiabilitiesLongTerm": 0.6,
          "shareholdersEquity": 153.168
        },
        {
          "period": "2024-03-31",
          "sourceRow": 8,
          "nopat": 12.050683353310301,
          "cashAndShortTermInvestments": 58.12,
          "totalDebt": 37.633,
          "operatingLeaseLiabilities": 19.246,
          "financeLeaseLiabilitiesCurrent": 0.08651912568306011,
          "financeLeaseLiabilitiesLongTerm": 0.6082049180327869,
          "shareholdersEquity": 149.529
        },
        {
          "period": "2024-06-30",
          "sourceRow": 9,
          "nopat": 13.234135773864688,
          "cashAndShortTermInvestments": 58.08,
          "totalDebt": 37.991,
          "operatingLeaseLiabilities": 19.602,
          "financeLeaseLiabilitiesCurrent": 0.08303825136612022,
          "financeLeaseLiabilitiesLongTerm": 0.6164098360655736,
          "shareholdersEquity": 156.763
        },
        {
          "period": "2024-09-30",
          "sourceRow": 10,
          "nopat": 15.272517113679722,
          "cashAndShortTermInvestments": 70.9,
          "totalDebt": 49.047,
          "operatingLeaseLiabilities": 20.224,
          "financeLeaseLiabilitiesCurrent": 0.0795191256830601,
          "financeLeaseLiabilitiesLongTerm": 0.6247049180327869,
          "shareholdersEquity": 164.529
        },
        {
          "period": "2024-12-31",
          "sourceRow": 11,
          "nopat": 20.67167112469749,
          "cashAndShortTermInvestments": 77.815,
          "totalDebt": 49.769,
          "operatingLeaseLiabilities": 20.234,
          "financeLeaseLiabilitiesCurrent": 0.076,
          "financeLeaseLiabilitiesLongTerm": 0.633,
          "shareholdersEquity": 182.637
        },
        {
          "period": "2025-03-31",
          "sourceRow": 12,
          "nopat": 15.895192035687087,
          "cashAndShortTermInvestments": 70.23,
          "totalDebt": 49.519,
          "operatingLeaseLiabilities": 20.69,
          "financeLeaseLiabilitiesCurrent": 0.13320547945205477,
          "financeLeaseLiabilitiesLongTerm": 0.692917808219178,
          "shareholdersEquity": 185.029
        },
        {
          "period": "2025-06-30",
          "sourceRow": 13,
          "nopat": 18.253950374987824,
          "cashAndShortTermInvestments": 47.071,
          "totalDebt": 49.56,
          "operatingLeaseLiabilities": 20.728,
          "financeLeaseLiabilitiesCurrent": 0.19104657534246575,
          "financeLeaseLiabilitiesLongTerm": 0.7535013698630137,
          "shareholdersEquity": 195.07
        },
        {
          "period": "2025-09-30",
          "sourceRow": 14,
          "nopat": 2.5679414208558375,
          "cashAndShortTermInvestments": 44.448,
          "totalDebt": 51.06,
          "operatingLeaseLiabilities": 22.226,
          "financeLeaseLiabilitiesCurrent": 0.24952328767123289,
          "financeLeaseLiabilitiesLongTerm": 0.8147506849315068,
          "shareholdersEquity": 194.066
        },
        {
          "period": "2025-12-31",
          "sourceRow": 15,
          "nopat": 22.22111540585312,
          "cashAndShortTermInvestments": 81.592,
          "totalDebt": 85.081,
          "operatingLeaseLiabilities": 25.153,
          "financeLeaseLiabilitiesCurrent": 0.308,
          "financeLeaseLiabilitiesLongTerm": 0.876,
          "shareholdersEquity": 217.243
        },
        {
          "period": "2026-03-31",
          "sourceRow": 16,
          "nopat": 27.60436532555011,
          "cashAndShortTermInvestments": 81.18,
          "totalDebt": 86.769,
          "operatingLeaseLiabilities": 28.021,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": 243.681
        },
        {
          "period": "2026-06-30",
          "sourceRow": 17,
          "nopat": 15.864187512346476,
          "cashAndShortTermInvestments": 90.26,
          "totalDebt": 112.318,
          "operatingLeaseLiabilities": 28.654,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": 261.221
        }
      ]
    },
    {
      "ticker": "ORCL",
      "name": "Oracle",
      "readiness": "ready",
      "readinessReason": "Direct Bloomberg NOPAT and core invested-capital fields available; latest period is March 2026 and remains calendarized.",
      "financeLeasesExcludedFromDebt": null,
      "quarters": [
        {
          "period": "2022-12-31",
          "sourceRow": 3,
          "nopat": 2.6307118261519498,
          "cashAndShortTermInvestments": 7.838766666666666,
          "totalDebt": 91.22624444444446,
          "operatingLeaseLiabilities": 4.368975342465753,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": -3.133955555555555
        },
        {
          "period": "2023-03-31",
          "sourceRow": 4,
          "nopat": 3.3339778427962994,
          "cashAndShortTermInvestments": 9.246804347826085,
          "totalDebt": 93.00214130434783,
          "operatingLeaseLiabilities": 4.664619178082192,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": -0.7434347826086956
        },
        {
          "period": "2023-06-30",
          "sourceRow": 5,
          "nopat": 3.9347023197069944,
          "cashAndShortTermInvestments": 10.805260869565217,
          "totalDebt": 93.25741304347825,
          "operatingLeaseLiabilities": 5.089180327868853,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": 1.9750217391304348
        },
        {
          "period": "2023-09-30",
          "sourceRow": 6,
          "nopat": 3.358920479247222,
          "cashAndShortTermInvestments": 10.96442857142857,
          "totalDebt": 88.89089010989011,
          "operatingLeaseLiabilities": 5.776666666666666,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": 3.3477032967032967
        },
        {
          "period": "2023-12-31",
          "sourceRow": 7,
          "nopat": 3.3036281353365062,
          "cashAndShortTermInvestments": 9.10356043956044,
          "totalDebt": 88.5134065934066,
          "operatingLeaseLiabilities": 6.464153005464482,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": 4.9925494505494505
        },
        {
          "period": "2024-03-31",
          "sourceRow": 8,
          "nopat": 3.3839147105278458,
          "cashAndShortTermInvestments": 10.159076086956523,
          "totalDebt": 90.16651086956522,
          "operatingLeaseLiabilities": 7.144166666666667,
          "financeLeaseLiabilitiesCurrent": 0.0,
          "financeLeaseLiabilitiesLongTerm": 0.0,
          "shareholdersEquity": 7.212076086956522
        },
        {
          "period": "2024-06-30",
          "sourceRow": 9,
          "nopat": 3.7835280692444813,
          "cashAndShortTermInvestments": 10.742521739130433,
          "totalDebt": 91.2231304347826,
          "operatingLeaseLiabilities": 8.080821917808219,
          "financeLeaseLiabilitiesCurrent": 0.021123287671232876,
          "financeLeaseLiabilitiesLongTerm": 0.22002739726027395,
          "shareholdersEquity": 9.90095652173913
        },
        {
          "period": "2024-09-30",
          "sourceRow": 10,
          "nopat": 3.779077037625216,
          "cashAndShortTermInvestments": 11.042868131868131,
          "totalDebt": 85.86961538461539,
          "operatingLeaseLiabilities": 9.555342465753425,
          "financeLeaseLiabilitiesCurrent": 0.0859013698630137,
          "financeLeaseLiabilitiesLongTerm": 0.8947780821917808,
          "shareholdersEquity": 12.247131868131866
        },
        {
          "period": "2024-12-31",
          "sourceRow": 11,
          "nopat": 3.9087075131049946,
          "cashAndShortTermInvestments": 13.55402222222222,
          "totalDebt": 91.2596888888889,
          "operatingLeaseLiabilities": 11.02986301369863,
          "financeLeaseLiabilitiesCurrent": 0.15067945205479452,
          "financeLeaseLiabilitiesLongTerm": 1.5695287671232876,
          "shareholdersEquity": 15.277944444444445
        },
        {
          "period": "2025-03-31",
          "sourceRow": 12,
          "nopat": 3.8531930155645666,
          "cashAndShortTermInvestments": 15.592347826086955,
          "totalDebt": 100.54726086956522,
          "operatingLeaseLiabilities": 12.472328767123289,
          "financeLeaseLiabilitiesCurrent": 0.21404931506849315,
          "financeLeaseLiabilitiesLongTerm": 2.2296109589041095,
          "shareholdersEquity": 18.510434782608694
        },
        {
          "period": "2025-06-30",
          "sourceRow": 13,
          "nopat": 3.9874574100904896,
          "cashAndShortTermInvestments": 11.138434782608696,
          "totalDebt": 108.51276086956521,
          "operatingLeaseLiabilities": 14.37608695652174,
          "financeLeaseLiabilitiesCurrent": 0.287989010989011,
          "financeLeaseLiabilitiesLongTerm": 3.0104065934065933,
          "shareholdersEquity": 22.174543478260873
        },
        {
          "period": "2025-09-30",
          "sourceRow": 14,
          "nopat": 4.032955693592769,
          "cashAndShortTermInvestments": 13.893241758241757,
          "totalDebt": 113.91785714285714,
          "operatingLeaseLiabilities": 17.077582417582416,
          "financeLeaseLiabilitiesCurrent": 0.383021978021978,
          "financeLeaseLiabilitiesLongTerm": 4.032853479853481,
          "shareholdersEquity": 26.575120879120878
        },
        {
          "period": "2025-12-31",
          "sourceRow": 15,
          "nopat": 4.722324139818826,
          "cashAndShortTermInvestments": 26.43651111111111,
          "totalDebt": 138.95112222222224,
          "operatingLeaseLiabilities": 19.58523333333333,
          "financeLeaseLiabilitiesCurrent": 0.47805494505494506,
          "financeLeaseLiabilitiesLongTerm": 5.055300366300367,
          "shareholdersEquity": 33.41715555555556
        },
        {
          "period": "2026-03-31",
          "sourceRow": 16,
          "nopat": 4.670180255213717,
          "cashAndShortTermInvestments": 36.69310869565217,
          "totalDebt": 163.93975,
          "operatingLeaseLiabilities": 24.30217391304348,
          "financeLeaseLiabilitiesCurrent": 0.5662934782608695,
          "financeLeaseLiabilitiesLongTerm": 6.172630434782608,
          "shareholdersEquity": 40.40051086956522
        },
        {
          "period": "2026-06-30",
          "sourceRow": 17,
          "nopat": null,
          "cashAndShortTermInvestments": null,
          "totalDebt": null,
          "operatingLeaseLiabilities": null,
          "financeLeaseLiabilitiesCurrent": null,
          "financeLeaseLiabilitiesLongTerm": null,
          "shareholdersEquity": null
        }
      ]
    }
  ]
} as const;
