// Generated by scripts/extract-sustainability.py. Do not edit inputs manually.
export const sustainabilitySnapshot = {
  "source": "Indexlist.xlsx",
  "sheet": "Hyperscaler Core Data Value",
  "sha256": "7bcb82c93af01c0fe8dd65123c1b5b9fbfff05755f8d012e5f36402aff99110e",
  "unit": "USD billions",
  "basis": "Cached Bloomberg BQ data; Oracle calendarization requires reconciliation.",
  "companies": [
    {
      "ticker": "MSFT",
      "name": "Microsoft",
      "quarters": [
        {
          "period": "2022-12-31",
          "cfo": null,
          "capex": null,
          "sourceRange": "E3:F3"
        },
        {
          "period": "2023-03-31",
          "cfo": 24.441,
          "capex": 6.607,
          "sourceRange": "E4:F4"
        },
        {
          "period": "2023-06-30",
          "cfo": 28.77,
          "capex": 8.943,
          "sourceRange": "E5:F5"
        },
        {
          "period": "2023-09-30",
          "cfo": 30.583,
          "capex": 9.917,
          "sourceRange": "E6:F6"
        },
        {
          "period": "2023-12-31",
          "cfo": 18.853,
          "capex": 9.735,
          "sourceRange": "E7:F7"
        },
        {
          "period": "2024-03-31",
          "cfo": 31.917,
          "capex": 10.952,
          "sourceRange": "E8:F8"
        },
        {
          "period": "2024-06-30",
          "cfo": 37.195,
          "capex": 13.873,
          "sourceRange": "E9:F9"
        },
        {
          "period": "2024-09-30",
          "cfo": 34.18,
          "capex": 14.923,
          "sourceRange": "E10:F10"
        },
        {
          "period": "2024-12-31",
          "cfo": 22.291,
          "capex": 15.804,
          "sourceRange": "E11:F11"
        },
        {
          "period": "2025-03-31",
          "cfo": 37.044,
          "capex": 16.745,
          "sourceRange": "E12:F12"
        },
        {
          "period": "2025-06-30",
          "cfo": 42.647,
          "capex": 17.079,
          "sourceRange": "E13:F13"
        },
        {
          "period": "2025-09-30",
          "cfo": 45.057,
          "capex": 19.394,
          "sourceRange": "E14:F14"
        },
        {
          "period": "2025-12-31",
          "cfo": 35.758,
          "capex": 29.876,
          "sourceRange": "E15:F15"
        },
        {
          "period": "2026-03-31",
          "cfo": 46.679,
          "capex": 30.876,
          "sourceRange": "E16:F16"
        },
        {
          "period": "2026-06-30",
          "cfo": 55.441,
          "capex": 35.802,
          "sourceRange": "E17:F17"
        }
      ]
    },
    {
      "ticker": "GOOGL",
      "name": "Alphabet",
      "quarters": [
        {
          "period": "2022-12-31",
          "cfo": null,
          "capex": null,
          "sourceRange": "P3:Q3"
        },
        {
          "period": "2023-03-31",
          "cfo": 23.509,
          "capex": 6.289,
          "sourceRange": "P4:Q4"
        },
        {
          "period": "2023-06-30",
          "cfo": 28.666,
          "capex": 6.888,
          "sourceRange": "P5:Q5"
        },
        {
          "period": "2023-09-30",
          "cfo": 30.656,
          "capex": 8.055,
          "sourceRange": "P6:Q6"
        },
        {
          "period": "2023-12-31",
          "cfo": 18.915,
          "capex": 11.019,
          "sourceRange": "P7:Q7"
        },
        {
          "period": "2024-03-31",
          "cfo": 28.848,
          "capex": 12.012,
          "sourceRange": "P8:Q8"
        },
        {
          "period": "2024-06-30",
          "cfo": 26.64,
          "capex": 13.186,
          "sourceRange": "P9:Q9"
        },
        {
          "period": "2024-09-30",
          "cfo": 30.698,
          "capex": 13.061,
          "sourceRange": "P10:Q10"
        },
        {
          "period": "2024-12-31",
          "cfo": 39.113,
          "capex": 14.276,
          "sourceRange": "P11:Q11"
        },
        {
          "period": "2025-03-31",
          "cfo": 36.15,
          "capex": 17.197,
          "sourceRange": "P12:Q12"
        },
        {
          "period": "2025-06-30",
          "cfo": 27.747,
          "capex": 22.446,
          "sourceRange": "P13:Q13"
        },
        {
          "period": "2025-09-30",
          "cfo": 48.414,
          "capex": 23.953,
          "sourceRange": "P14:Q14"
        },
        {
          "period": "2025-12-31",
          "cfo": 52.402,
          "capex": 27.851,
          "sourceRange": "P15:Q15"
        },
        {
          "period": "2026-03-31",
          "cfo": 45.79,
          "capex": 35.674,
          "sourceRange": "P16:Q16"
        },
        {
          "period": "2026-06-30",
          "cfo": 39.069,
          "capex": 44.924,
          "sourceRange": "P17:Q17"
        }
      ]
    },
    {
      "ticker": "AMZN",
      "name": "Amazon",
      "quarters": [
        {
          "period": "2022-12-31",
          "cfo": null,
          "capex": null,
          "sourceRange": "AA3:AB3"
        },
        {
          "period": "2023-03-31",
          "cfo": 4.788,
          "capex": 14.207,
          "sourceRange": "AA4:AB4"
        },
        {
          "period": "2023-06-30",
          "cfo": 16.476,
          "capex": 11.455,
          "sourceRange": "AA5:AB5"
        },
        {
          "period": "2023-09-30",
          "cfo": 21.217,
          "capex": 12.479,
          "sourceRange": "AA6:AB6"
        },
        {
          "period": "2023-12-31",
          "cfo": 42.465,
          "capex": 14.588,
          "sourceRange": "AA7:AB7"
        },
        {
          "period": "2024-03-31",
          "cfo": 18.989,
          "capex": 14.925,
          "sourceRange": "AA8:AB8"
        },
        {
          "period": "2024-06-30",
          "cfo": 25.281,
          "capex": 17.62,
          "sourceRange": "AA9:AB9"
        },
        {
          "period": "2024-09-30",
          "cfo": 25.971,
          "capex": 22.62,
          "sourceRange": "AA10:AB10"
        },
        {
          "period": "2024-12-31",
          "cfo": 45.636,
          "capex": 27.834,
          "sourceRange": "AA11:AB11"
        },
        {
          "period": "2025-03-31",
          "cfo": 17.015,
          "capex": 25.019,
          "sourceRange": "AA12:AB12"
        },
        {
          "period": "2025-06-30",
          "cfo": 32.515,
          "capex": 32.183,
          "sourceRange": "AA13:AB13"
        },
        {
          "period": "2025-09-30",
          "cfo": 35.525,
          "capex": 35.095,
          "sourceRange": "AA14:AB14"
        },
        {
          "period": "2025-12-31",
          "cfo": 54.459,
          "capex": 39.522,
          "sourceRange": "AA15:AB15"
        },
        {
          "period": "2026-03-31",
          "cfo": 26.032,
          "capex": 44.203,
          "sourceRange": "AA16:AB16"
        },
        {
          "period": "2026-06-30",
          "cfo": 45.387,
          "capex": 54.208,
          "sourceRange": "AA17:AB17"
        }
      ]
    },
    {
      "ticker": "META",
      "name": "Meta",
      "quarters": [
        {
          "period": "2022-12-31",
          "cfo": null,
          "capex": null,
          "sourceRange": "AL3:AM3"
        },
        {
          "period": "2023-03-31",
          "cfo": 13.998,
          "capex": 6.842,
          "sourceRange": "AL4:AM4"
        },
        {
          "period": "2023-06-30",
          "cfo": 17.309,
          "capex": 6.216,
          "sourceRange": "AL5:AM5"
        },
        {
          "period": "2023-09-30",
          "cfo": 20.402,
          "capex": 6.543,
          "sourceRange": "AL6:AM6"
        },
        {
          "period": "2023-12-31",
          "cfo": 19.404,
          "capex": 7.665,
          "sourceRange": "AL7:AM7"
        },
        {
          "period": "2024-03-31",
          "cfo": 19.246,
          "capex": 6.4,
          "sourceRange": "AL8:AM8"
        },
        {
          "period": "2024-06-30",
          "cfo": 19.37,
          "capex": 8.173,
          "sourceRange": "AL9:AM9"
        },
        {
          "period": "2024-09-30",
          "cfo": 24.724,
          "capex": 8.258,
          "sourceRange": "AL10:AM10"
        },
        {
          "period": "2024-12-31",
          "cfo": 27.988,
          "capex": 14.425,
          "sourceRange": "AL11:AM11"
        },
        {
          "period": "2025-03-31",
          "cfo": 24.026,
          "capex": 12.941,
          "sourceRange": "AL12:AM12"
        },
        {
          "period": "2025-06-30",
          "cfo": 25.561,
          "capex": 16.538,
          "sourceRange": "AL13:AM13"
        },
        {
          "period": "2025-09-30",
          "cfo": 29.999,
          "capex": 18.829,
          "sourceRange": "AL14:AM14"
        },
        {
          "period": "2025-12-31",
          "cfo": 36.214,
          "capex": 21.383,
          "sourceRange": "AL15:AM15"
        },
        {
          "period": "2026-03-31",
          "cfo": 32.226,
          "capex": 18.997,
          "sourceRange": "AL16:AM16"
        },
        {
          "period": "2026-06-30",
          "cfo": 31.862,
          "capex": 30.116,
          "sourceRange": "AL17:AM17"
        }
      ]
    },
    {
      "ticker": "ORCL",
      "name": "Oracle",
      "quarters": [
        {
          "period": "2022-12-31",
          "cfo": 2.04160989010989,
          "capex": 2.5374527472527473,
          "sourceRange": "AW3:AX3"
        },
        {
          "period": "2023-03-31",
          "cfo": 4.70529347826087,
          "capex": 2.3673978260869566,
          "sourceRange": "AW4:AX4"
        },
        {
          "period": "2023-06-30",
          "cfo": 6.018336956521738,
          "capex": 1.6968804347826085,
          "sourceRange": "AW5:AX5"
        },
        {
          "period": "2023-09-30",
          "cfo": 4.747012422360249,
          "capex": 1.2415656951743907,
          "sourceRange": "AW6:AX6"
        },
        {
          "period": "2023-12-31",
          "cfo": 1.9609670329670332,
          "capex": 1.2942197802197801,
          "sourceRange": "AW7:AX7"
        },
        {
          "period": "2024-03-31",
          "cfo": 5.658922718585762,
          "capex": 2.046540611562351,
          "sourceRange": "AW8:AX8"
        },
        {
          "period": "2024-06-30",
          "cfo": 6.453815217391304,
          "capex": 2.6061739130434782,
          "sourceRange": "AW9:AX9"
        },
        {
          "period": "2024-09-30",
          "cfo": 5.435042283803153,
          "capex": 2.860812947921643,
          "sourceRange": "AW10:AX10"
        },
        {
          "period": "2024-12-31",
          "cfo": 2.917698778998779,
          "capex": 4.680342124542124,
          "sourceRange": "AW11:AX11"
        },
        {
          "period": "2025-03-31",
          "cfo": 5.964052415458936,
          "capex": 6.902431884057971,
          "sourceRange": "AW12:AX12"
        },
        {
          "period": "2025-06-30",
          "cfo": 6.73670652173913,
          "capex": 8.79282608695652,
          "sourceRange": "AW13:AX13"
        },
        {
          "period": "2025-09-30",
          "cfo": 6.166751075011944,
          "capex": 9.69653177257525,
          "sourceRange": "AW14:AX14"
        },
        {
          "period": "2025-12-31",
          "cfo": 3.8480233211233212,
          "capex": 14.484799145299144,
          "sourceRange": "AW15:AX15"
        },
        {
          "period": "2026-03-31",
          "cfo": 9.614182125603865,
          "capex": 17.77370169082126,
          "sourceRange": "AW16:AX16"
        },
        {
          "period": "2026-06-30",
          "cfo": null,
          "capex": null,
          "sourceRange": "AW17:AX17"
        }
      ]
    }
  ]
};
