// Generated by scripts/build-task-economics-snapshot.py. Do not edit manually.
export const taskEconomicsSnapshot = {
  "metadata": {
    "source": "Epoch AI \u2014 frontier_ai_models.csv and ml_hardware.csv",
    "retrievedAt": "2026-09-29T02:19:13.848002+00:00",
    "modelDatasetAsOf": "2026-09-03",
    "costObservationAsOf": "2025-07-09",
    "observationCount": 48,
    "costBasis": "Estimated training compute cost in constant 2023 USD as reported by Epoch AI."
  },
  "observations": [
    {
      "date": "2017-07-10",
      "model": "JFT",
      "lab": "Google",
      "organization": "Google Research,Carnegie Mellon University (CMU)",
      "trainingCost": 17910.759507843868,
      "trainingCompute": 8.43e+20,
      "hardware": "NVIDIA Tesla K80",
      "confidence": "Confident"
    },
    {
      "date": "2017-10-18",
      "model": "AlphaGo Zero",
      "lab": "Google",
      "organization": "DeepMind",
      "trainingCost": 1213.8707315707268,
      "trainingCompute": 6.49439910290227e+20,
      "hardware": "Google TPU v1",
      "confidence": "Confident"
    },
    {
      "date": "2018-05-02",
      "model": "ResNeXt-101 32x48d",
      "lab": "Facebook",
      "organization": "Facebook",
      "trainingCost": 134077.42688552555,
      "trainingCompute": 8.74395e+21,
      "hardware": "NVIDIA V100",
      "confidence": "Confident"
    },
    {
      "date": "2018-09-28",
      "model": "BigGAN-deep 512x512",
      "lab": "Heriot-Watt University",
      "organization": "Heriot-Watt University,DeepMind",
      "trainingCost": 5371.7513177697365,
      "trainingCompute": 1.8e+21,
      "hardware": "Google TPU v3",
      "confidence": "Likely"
    },
    {
      "date": "2019-02-14",
      "model": "GPT-2 (355M)",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 8649.049000458455,
      "trainingCompute": 2.272000000071e+21,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2019-02-14",
      "model": "GPT-2 (774M)",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 18857.363172241257,
      "trainingCompute": 4.9536e+21,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2019-05-29",
      "model": "Grover-Mega",
      "lab": "University of Washington",
      "organization": "University of Washington",
      "trainingCost": 15691.613136656455,
      "trainingCompute": 4.6386183e+21,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-06-01",
      "model": "XLNet",
      "lab": "Carnegie Mellon University (CMU)",
      "organization": "Carnegie Mellon University (CMU),Google Brain",
      "trainingCost": 13644.959135438661,
      "trainingCompute": 6.19e+21,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-07-01",
      "model": "RoBERTa Large",
      "lab": "Facebook",
      "organization": "Facebook,University of Washington",
      "trainingCost": 85350.2350127364,
      "trainingCompute": 8.5067e+21,
      "hardware": "NVIDIA Tesla V100 DGXS 32 GB",
      "confidence": "Confident"
    },
    {
      "date": "2019-09-17",
      "model": "Megatron-LM (8.3B)",
      "lab": "NVIDIA",
      "organization": "Nvidia",
      "trainingCost": 109287.55758939347,
      "trainingCompute": 9.1e+21,
      "hardware": "NVIDIA Tesla V100 DGXS 32 GB",
      "confidence": "Likely"
    },
    {
      "date": "2019-09-17",
      "model": "Megatron-BERT",
      "lab": "NVIDIA",
      "organization": "Nvidia",
      "trainingCost": 171818.64196707975,
      "trainingCompute": 2.2e+22,
      "hardware": "NVIDIA Tesla V100S PCIe 32 GB",
      "confidence": "Confident"
    },
    {
      "date": "2019-10-23",
      "model": "T5-3B",
      "lab": "Google",
      "organization": "Google",
      "trainingCost": 17420.709393371122,
      "trainingCompute": 9.0000000001e+21,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-10-23",
      "model": "T5-11B",
      "lab": "Google",
      "organization": "Google",
      "trainingCost": 78464.68282814459,
      "trainingCompute": 3.3e+22,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-10-30",
      "model": "AlphaStar",
      "lab": "Google",
      "organization": "DeepMind",
      "trainingCost": 130654.07330431018,
      "trainingCompute": 1.0773400001e+23,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-11-05",
      "model": "XLM-RoBERTa",
      "lab": "Meta",
      "organization": "Facebook AI",
      "trainingCost": 77861.31819548723,
      "trainingCompute": 2.076e+22,
      "hardware": "NVIDIA Tesla V100 DGXS 32 GB",
      "confidence": "Confident"
    },
    {
      "date": "2019-11-11",
      "model": "Noisy Student (L2)",
      "lab": "Carnegie Mellon University (CMU)",
      "organization": "Carnegie Mellon University (CMU),Google",
      "trainingCost": 45609.73119622589,
      "trainingCompute": 2.612e+22,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2019-12-13",
      "model": "OpenAI Five",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 4328311.470477086,
      "trainingCompute": 6.7e+22,
      "hardware": "NVIDIA P100",
      "confidence": "Confident"
    },
    {
      "date": "2020-01-28",
      "model": "Meena",
      "lab": "Google",
      "organization": "Google Brain",
      "trainingCost": 214809.91213508433,
      "trainingCompute": 1.12e+23,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2020-05-28",
      "model": "GPT-3 175B (davinci)",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 2116866.2428390156,
      "trainingCompute": 3.14e+23,
      "hardware": "NVIDIA Tesla V100 DGXS 32 GB",
      "confidence": "Confident"
    },
    {
      "date": "2020-06-17",
      "model": "iGPT-XL",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 100796.41431883824,
      "trainingCompute": 3.3e+22,
      "hardware": "NVIDIA Tesla V100 DGXS 32 GB",
      "confidence": "Likely"
    },
    {
      "date": "2020-06-30",
      "model": "GShard (dense)",
      "lab": "Google",
      "organization": "Google",
      "trainingCost": 266200.0315979732,
      "trainingCompute": 4.765e+22,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2020-10-20",
      "model": "mT5-XXL",
      "lab": "Google",
      "organization": "Google,Google Research",
      "trainingCost": 179442.0291399545,
      "trainingCompute": 8.2e+22,
      "hardware": "Not disclosed",
      "confidence": "Confident"
    },
    {
      "date": "2021-01-11",
      "model": "Switch",
      "lab": "Google",
      "organization": "Google",
      "trainingCost": 145100.89767585773,
      "trainingCompute": 8.22e+22,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2021-05-31",
      "model": "Wu Dao 2.0",
      "lab": "Beijing Academy of Artificial Intelligence / BAAI",
      "organization": "Beijing Academy of Artificial Intelligence / BAAI",
      "trainingCost": 2870839.8244998017,
      "trainingCompute": 1.54350000000001e+24,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2021-08-11",
      "model": "Jurassic-1-Jumbo",
      "lab": "AI21 Labs",
      "organization": "AI21 Labs",
      "trainingCost": 836700.050829598,
      "trainingCompute": 3.7e+23,
      "hardware": "NVIDIA A100",
      "confidence": "Confident"
    },
    {
      "date": "2021-09-10",
      "model": "HyperCLOVA 204B",
      "lab": "NAVER",
      "organization": "NAVER",
      "trainingCost": 441770.0038182093,
      "trainingCompute": 2.0000000001e+23,
      "hardware": "NVIDIA A100",
      "confidence": "Speculative"
    },
    {
      "date": "2021-10-11",
      "model": "Megatron-Turing NLG 530B",
      "lab": "Microsoft",
      "organization": "Microsoft,Nvidia",
      "trainingCost": 3848505.6256471733,
      "trainingCompute": 8.586e+23,
      "hardware": "NVIDIA A100 SXM4 80 GB",
      "confidence": "Confident"
    },
    {
      "date": "2021-10-12",
      "model": "Yuan 1.0",
      "lab": "Inspur",
      "organization": "Inspur",
      "trainingCost": 591664.5798708292,
      "trainingCompute": 3.5380000000001e+23,
      "hardware": "Not disclosed",
      "confidence": "Confident"
    },
    {
      "date": "2021-12-08",
      "model": "Gopher (280B)",
      "lab": "Google",
      "organization": "DeepMind",
      "trainingCost": 640616.8522346151,
      "trainingCompute": 6.31e+23,
      "hardware": "Google TPU v3",
      "confidence": "Confident"
    },
    {
      "date": "2021-12-14",
      "model": "EXAONE 1.0",
      "lab": "LG",
      "organization": "LG",
      "trainingCost": 2702636.2890818655,
      "trainingCompute": 1.6956e+24,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2022-03-15",
      "model": "GPT-3.5 (davinci-002)",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 4897551.634095244,
      "trainingCompute": 2.578e+24,
      "hardware": "NVIDIA A100 SXM4 40 GB",
      "confidence": "Speculative"
    },
    {
      "date": "2022-04-04",
      "model": "PaLM (540B)",
      "lab": "Google",
      "organization": "Google Research",
      "trainingCost": 3060364.5969860666,
      "trainingCompute": 2.5272e+24,
      "hardware": "Google TPU v4",
      "confidence": "Confident"
    },
    {
      "date": "2023-03-15",
      "model": "GPT-4 (Mar 2023)",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 37334304.976625234,
      "trainingCompute": 2.1e+25,
      "hardware": "NVIDIA A100 SXM4 40 GB",
      "confidence": "Likely"
    },
    {
      "date": "2023-04-10",
      "model": "SenseChat",
      "lab": "SenseTime",
      "organization": "SenseTime",
      "trainingCost": 5328550.47393551,
      "trainingCompute": 3.89e+24,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2023-05-10",
      "model": "PaLM 2",
      "lab": "Google",
      "organization": "Google",
      "trainingCost": 5014266.983518871,
      "trainingCompute": 7.34e+24,
      "hardware": "Google TPU v4",
      "confidence": "Likely"
    },
    {
      "date": "2023-07-11",
      "model": "Claude 2",
      "lab": "Anthropic",
      "organization": "Anthropic",
      "trainingCost": 4902644.123383027,
      "trainingCompute": 3.866e+24,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2023-09-06",
      "model": "Falcon-180B",
      "lab": "Technology Innovation Institute",
      "organization": "Technology Innovation Institute",
      "trainingCost": 10743500.868805483,
      "trainingCompute": 3.76e+24,
      "hardware": "NVIDIA A100 SXM4 40 GB",
      "confidence": "Confident"
    },
    {
      "date": "2023-09-28",
      "model": "Amazon Titan",
      "lab": "Amazon",
      "organization": "Amazon",
      "trainingCost": 7933464.673729055,
      "trainingCompute": 4.8e+24,
      "hardware": "NVIDIA A100",
      "confidence": "Likely"
    },
    {
      "date": "2023-11-22",
      "model": "Inflection-2",
      "lab": "Inflection AI",
      "organization": "Inflection AI",
      "trainingCost": 13461144.182562498,
      "trainingCompute": 1.001e+25,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Confident"
    },
    {
      "date": "2023-12-06",
      "model": "Gemini 1.0 Ultra",
      "lab": "Google",
      "organization": "Google DeepMind",
      "trainingCost": 30719419.93534952,
      "trainingCompute": 5.0000000001e+25,
      "hardware": "Google TPU v4",
      "confidence": "Speculative"
    },
    {
      "date": "2024-06-14",
      "model": "Nemotron-4 340B",
      "lab": "NVIDIA",
      "organization": "Nvidia",
      "trainingCost": 21271017.96222655,
      "trainingCompute": 1.8e+25,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Confident"
    },
    {
      "date": "2024-06-20",
      "model": "Claude 3.5 Sonnet",
      "lab": "Anthropic",
      "organization": "Anthropic",
      "trainingCost": 25870993.12024943,
      "trainingCompute": 2.700000000000001e+25,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    },
    {
      "date": "2024-07-23",
      "model": "Llama 3.1-405B",
      "lab": "Meta",
      "organization": "Meta AI",
      "trainingCost": 52885433.95402246,
      "trainingCompute": 3.8e+25,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Confident"
    },
    {
      "date": "2024-08-13",
      "model": "Grok-2",
      "lab": "xAI",
      "organization": "xAI",
      "trainingCost": 31602310.530835517,
      "trainingCompute": 2.96e+25,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Confident"
    },
    {
      "date": "2025-02-17",
      "model": "Grok 3",
      "lab": "xAI",
      "organization": "xAI",
      "trainingCost": 217835545.5267339,
      "trainingCompute": 3.5e+26,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Likely"
    },
    {
      "date": "2025-02-27",
      "model": "GPT-4.5",
      "lab": "OpenAI",
      "organization": "OpenAI",
      "trainingCost": 366010627.6281514,
      "trainingCompute": 3.8e+26,
      "hardware": "Not disclosed",
      "confidence": "Likely"
    },
    {
      "date": "2025-04-05",
      "model": "Llama 4 Behemoth (preview)",
      "lab": "Meta",
      "organization": "Meta AI",
      "trainingCost": 44588963.624007165,
      "trainingCompute": 5.18400000000001e+25,
      "hardware": "NVIDIA H100 SXM5 80GB",
      "confidence": "Likely"
    },
    {
      "date": "2025-07-09",
      "model": "Grok 4",
      "lab": "xAI",
      "organization": "xAI",
      "trainingCost": 387842678.08636147,
      "trainingCompute": 5.0000000000001e+26,
      "hardware": "Not disclosed",
      "confidence": "Speculative"
    }
  ],
  "annualRanges": [
    {
      "year": 2017,
      "count": 2,
      "min": 1213.8707315707268,
      "p25": 5388.092925639012,
      "median": 9562.315119707297,
      "p75": 13736.537313775583,
      "max": 17910.759507843868
    },
    {
      "year": 2018,
      "count": 2,
      "min": 5371.7513177697365,
      "p25": 37548.17020970869,
      "median": 69724.58910164764,
      "p75": 101901.0079935866,
      "max": 134077.42688552555
    },
    {
      "year": 2019,
      "count": 13,
      "min": 8649.049000458455,
      "p25": 17420.709393371122,
      "median": 77861.31819548723,
      "p75": 109287.55758939347,
      "max": 4328311.470477086
    },
    {
      "year": 2020,
      "count": 5,
      "min": 100796.41431883824,
      "p25": 179442.0291399545,
      "median": 214809.91213508433,
      "p75": 266200.0315979732,
      "max": 2116866.2428390156
    },
    {
      "year": 2021,
      "count": 8,
      "min": 145100.89767585773,
      "p25": 554190.9358576742,
      "median": 738658.4515321066,
      "p75": 2744687.172936349,
      "max": 3848505.6256471733
    },
    {
      "year": 2022,
      "count": 2,
      "min": 3060364.5969860666,
      "p25": 3519661.356263361,
      "median": 3978958.1155406553,
      "p75": 4438254.87481795,
      "max": 4897551.634095244
    },
    {
      "year": 2023,
      "count": 8,
      "min": 4902644.123383027,
      "p25": 5249979.601331349,
      "median": 9338482.771267269,
      "p75": 17775713.120759252,
      "max": 37334304.976625234
    },
    {
      "year": 2024,
      "count": 4,
      "min": 21271017.96222655,
      "p25": 24720999.33074371,
      "median": 28736651.825542472,
      "p75": 36923091.386632256,
      "max": 52885433.95402246
    },
    {
      "year": 2025,
      "count": 4,
      "min": 44588963.624007165,
      "p25": 174523900.0510522,
      "median": 291923086.57744265,
      "p75": 371468640.2427039,
      "max": 387842678.08636147
    }
  ],
  "latest": {
    "date": "2025-07-09",
    "model": "Grok 4",
    "lab": "xAI",
    "organization": "xAI",
    "trainingCost": 387842678.08636147,
    "trainingCompute": 5.0000000000001e+26,
    "hardware": "Not disclosed",
    "confidence": "Speculative"
  },
  "highest": {
    "date": "2025-07-09",
    "model": "Grok 4",
    "lab": "xAI",
    "organization": "xAI",
    "trainingCost": 387842678.08636147,
    "trainingCompute": 5.0000000000001e+26,
    "hardware": "Not disclosed",
    "confidence": "Speculative"
  },
  "hardware": [
    {
      "name": "NVIDIA H100 SXM5 80GB",
      "manufacturer": "NVIDIA",
      "releaseDate": "2022-09-20",
      "releasePrice": 33600.0,
      "pricePerformance": 58898809523.809525,
      "energyEfficiency": 2827142857142.857,
      "memoryBytes": 80000000000.0
    },
    {
      "name": "AMD Instinct MI300X",
      "manufacturer": "AMD",
      "releaseDate": "2023-12-06",
      "releasePrice": 15000.0,
      "pricePerformance": 174326666666.66666,
      "energyEfficiency": 3486533333333.333,
      "memoryBytes": 192000000000.0
    },
    {
      "name": "NVIDIA H200 SXM",
      "manufacturer": "NVIDIA",
      "releaseDate": "2024-11-18",
      "releasePrice": 30000.0,
      "pricePerformance": 65966666666.66666,
      "energyEfficiency": 2827142857142.857,
      "memoryBytes": 141000000000.0
    },
    {
      "name": "NVIDIA GB200",
      "manufacturer": "NVIDIA",
      "releaseDate": "2025-02-15",
      "releasePrice": 37000.0,
      "pricePerformance": 135135135135.13512,
      "energyEfficiency": 8333333333333.333,
      "memoryBytes": 186000000000.0
    },
    {
      "name": "AMD Instinct MI355X",
      "manufacturer": "AMD",
      "releaseDate": "2025-06-12",
      "releasePrice": 30000.0,
      "pricePerformance": 167773333333.33334,
      "energyEfficiency": 7190214285714.286,
      "memoryBytes": 288000000000.0
    },
    {
      "name": "NVIDIA GB300 (Blackwell Ultra)",
      "manufacturer": "NVIDIA",
      "releaseDate": "2025-08-22",
      "releasePrice": 43000.0,
      "pricePerformance": 58139534883.72093,
      "energyEfficiency": 10714285714285.717,
      "memoryBytes": 287500000000.0
    },
    {
      "name": "Google TPU v7 Ironwood",
      "manufacturer": "Google",
      "releaseDate": "2025-11-06",
      "releasePrice": 12000.0,
      "pricePerformance": 192250000000.0,
      "energyEfficiency": 4806250000000.0,
      "memoryBytes": 192000000000.0
    }
  ],
  "recovery": {
    "contributionMargins": [
      0.3,
      0.5,
      0.7
    ],
    "models": [
      {
        "model": "Grok 4",
        "lab": "xAI",
        "date": "2025-07-09",
        "trainingCost": 387842678.08636147,
        "revenueRequired": [
          1292808927,
          775685356,
          554060969
        ]
      },
      {
        "model": "GPT-4.5",
        "lab": "OpenAI",
        "date": "2025-02-27",
        "trainingCost": 366010627.6281514,
        "revenueRequired": [
          1220035425,
          732021255,
          522872325
        ]
      },
      {
        "model": "Grok 3",
        "lab": "xAI",
        "date": "2025-02-17",
        "trainingCost": 217835545.5267339,
        "revenueRequired": [
          726118485,
          435671091,
          311193636
        ]
      },
      {
        "model": "Llama 3.1-405B",
        "lab": "Meta",
        "date": "2024-07-23",
        "trainingCost": 52885433.95402246,
        "revenueRequired": [
          176284780,
          105770868,
          75550620
        ]
      },
      {
        "model": "Llama 4 Behemoth (preview)",
        "lab": "Meta",
        "date": "2025-04-05",
        "trainingCost": 44588963.624007165,
        "revenueRequired": [
          148629879,
          89177927,
          63698519
        ]
      }
    ],
    "method": "Revenue required equals estimated training compute cost divided by assumed contribution margin."
  }
} as const;
