"use client";
import {useState} from "react";
import {industryChain} from "./industry-chain-data";
import {chainEconomicsSnapshot as data} from "./chain-economics-snapshot";
import {chainShares} from "./chain-economics";
import "./value-distribution.css";
const stages=[{title:"Applications & distribution",ids:["applications","platforms"]},{title:"Hardware & deployment",ids:["silicon","systems","datacenters","power"]},{title:"Components & manufacturing",ids:["foundry","memory","equipment"]}];
const amount=(v:number|null,c:string)=>v===null?"Unavailable":`${c} ${(v/1e9).toFixed(2)}B`;
const roleOrder=["applications","platforms","datacenters","systems","silicon","foundry","memory","equipment","power"];
const roleColors=["#193e63","#20857c","#557c9c","#7f6aab","#d5a53c","#b06a43","#67945f","#b65672","#5e8582"];
export default function ValueDistribution(){
 const [metric,setMetric]=useState<"revenue"|"ebitda">("revenue");
 const [period,setPeriod]=useState<string>(data.metadata.latestCommonPeriod!);
 const [currency,setCurrency]=useState("USD");
 const [selectedRole,setSelectedRole]=useState<string|null>(null);
 const result=chainShares(data.companies,period,currency,metric);
 const roles=roleOrder.map((id,i)=>{const g=industryChain.find(g=>g.id===id)!;const rows=result.rows.filter(r=>g.companies.some(c=>c.ticker===r.ticker)&&r.eligible);return {...g,color:roleColors[i],count:rows.length,total:rows.reduce((s,r)=>s+r.amount!,0),share:result.total>0&&rows.length?rows.reduce((s,r)=>s+(r.share??0),0):null};});
 const negative=roles.some(r=>r.total<0);
 const max=Math.max(...result.rows.map(r=>Math.abs(r.share??0)),1);
 return <div className="value-distribution ce-map">
 <div className="vd-intro"><div><span className="eyebrow">REPORTED FINANCIAL SCALE · {data.metadata.coverage} COVERED COMPANIES</span><h3>Revenue and EBITDA across the AI supply chain.</h3><p>Compare the economic scale of covered companies at a common trailing-12-month date. Company revenue includes non-AI businesses and overlapping supplier sales; these shares measure the covered financial universe, rather than payments received from AI investment.</p></div></div>
 <div className="ce-controls"><label>Financial measure<select value={metric} onChange={e=>setMetric(e.target.value as "revenue"|"ebitda")}><option value="revenue">TTM revenue</option><option value="ebitda">TTM EBITDA</option></select></label><label>TTM end date<select value={period} onChange={e=>setPeriod(e.target.value)}>{data.periods.map(p=><option key={p}>{p}</option>)}</select></label><label>Comparable currency group<select value={currency} onChange={e=>setCurrency(e.target.value)}>{[...new Set(Object.values(data.companies).map(c=>c.currency))].sort().map(c=><option key={c}>{c}</option>)}</select></label></div>
 <p className="ce-denominator"><b>{result.count} / {data.metadata.coverage} companies in the {currency} denominator · {amount(result.total,currency)}</b><br/>Percentages refer only to available {currency} amounts at this date. {data.metadata.usdQuery?"":"Full-universe shares are withheld until source amounts are converted to a common currency. The financial query currently uses “Currncy=USD”; the cached local-currency amounts are not comparable with USD."}</p>
 <p className="vd-note">Read from applications and platforms through hardware to its upstream suppliers. The arrangement represents industry relationships; it does not assign payment flows. Each company appears once in its assigned sector.</p>
 <div className="ce-role-map"><h4>Financial scale by value-chain role</h4><p>{currency} · TTM {metric === "revenue" ? "revenue" : "EBITDA"} · {period}. Select a role to inspect its companies.</p>
 {!negative&&result.total>0?<div className="ce-role-strip" aria-label="Value-chain roles sized by financial share">{roles.filter(r=>r.total>0).map(r=><button key={r.id} aria-label={`${r.title}: ${r.share?.toFixed(1)}%`} aria-pressed={selectedRole===r.id} title={`${r.title}: ${amount(r.total,currency)} · ${r.share?.toFixed(1)}%`} onClick={()=>setSelectedRole(selectedRole===r.id?null:r.id)} style={{width:`${r.share}%`,background:r.color}}>{r.share!>=7?<span>{r.title}<b>{r.share!.toFixed(1)}%</b></span>:null}</button>)}</div>:<p>Signed role totals are shown below; negative EBITDA contributions cannot be represented as segments of a 100% bar.</p>}
 <div className="ce-role-key">{roles.map(r=><button key={r.id} aria-pressed={selectedRole===r.id} onClick={()=>setSelectedRole(selectedRole===r.id?null:r.id)}><i style={{background:r.color}}/><span>{r.title}<small>{r.count}/{r.companies.length} in selected denominator</small></span><strong>{r.share===null?"—":`${r.share.toFixed(1)}%`}<small>{r.count?amount(r.total,currency):"Unavailable in this currency"}</small></strong></button>)}</div><p className="vd-note">Segment width is proportional to each role’s reported amount; small roles are identified in the legend. Shares describe the selected covered-company denominator, not transactions between roles.</p></div>
 {selectedRole&&<button className="data-button secondary" onClick={()=>setSelectedRole(null)}>Show all roles</button>}
 <div className="ce-stages">{stages.filter(stage=>!selectedRole||stage.ids.includes(selectedRole)).map(stage=><div key={stage.title}><h4>{stage.title}</h4>{industryChain.filter(g=>stage.ids.includes(g.id)&&(!selectedRole||g.id===selectedRole)).map(g=>{const rows=g.companies.map(c=>({...c,...result.rows.find(r=>r.ticker===c.ticker)!}));const eligible=rows.filter(r=>r.eligible);const share=eligible.reduce((s,r)=>s+(r.share??0),0);return <article className="ce-sector" key={g.id}><header><b>{g.title}</b><span>{eligible.length&&result.total>0?`${share.toFixed(1)}%`:"—"}</span></header>{rows.map(r=><div className="ce-company" key={r.ticker}><div><b>{r.name}</b><small>{r.ticker}</small></div><div><strong>{r.share===null?"—":`${r.share.toFixed(1)}%`}</strong><small>{amount(r.amount,r.currency)}</small></div><div className="ce-bar"><i style={{width:`${Math.abs(r.share??0)/max*100}%`,background:(r.share??0)<0?"#bd654c":"#20857c"}}/></div><small className="ce-status">{r.amount===null?"Incomplete TTM data":r.eligible?`${period} · ${r.sourceRange}`:"Outside selected currency denominator"}</small></div>)}</article>})}</div>)}</div>
 <details className="vd-sources"><summary>Sources and calculation boundaries</summary><p>Company share = company TTM amount / sum of available company TTM amounts in the selected currency group. TTM sums four consecutive calendarized source quarters; missing quarters remain unavailable. March 2026 is the latest complete common TTM date for all 36 companies. June lacks complete observations for AMD, ASML and Lam Research.</p><p>EBITDA shares retain negative contributions; a nonpositive total has no percentage calculation. EBITDA is before depreciation, interest and taxes, and does not measure capital returns. Revenue totals include intercompany sales and must not be interpreted as AI market size or value added. Private lab annualized revenue estimates are excluded from this comparable listed-company calculation.</p><p>{data.metadata.currencyMethod}</p><p>Source: {data.metadata.source} → {data.metadata.sheet}; extracted {data.metadata.extractedAt}. Source cells shown refer to each TTM ending observation; its preceding three quarters complete the window. SHA-256: <code>{data.metadata.sha256}</code>.</p></details>
 </div>
}
