(() => {
  'use strict';
  const D=JSON.parse(document.getElementById('research-data').textContent), host=document.getElementById('research-app');
  const pct=v=>v==null?'—':(v*100).toFixed(1)+'%', num=v=>v==null?'—':v.toFixed(1), change=(a,b)=>b>0?a/b-1:null;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sum=(a,k)=>a.every(x=>Number.isFinite(x[k]))?a.reduce((s,x)=>s+x[k],0):null;
  const qkey=m=>m.slice(0,4)+'Q'+Math.ceil(Number(m.slice(5))/3);
  const quarters=[...new Set(D.months.map(m=>qkey(m.month)))].map(q=>{const m=D.months.filter(m=>qkey(m.month)===q);return {quarter:q,total:sum(m,'total'),days:sum(m,'days'),complete:m.length===3&&m.every(x=>x.complete)};});
  function company(ticker) {
    const rows=D.financial[ticker];
    return rows.map((r,i)=>{
      const window=rows.slice(i-3,i+1), valid=i>=4&&rows[i-4].date.slice(0,4)==String(Number(r.date.slice(0,4))-1)&&rows[i-4].date.slice(5)===r.date.slice(5);
      if(!valid)return {...r,roic:null};
      const capital=(r.ic+rows[i-4].ic)/2, nopat=sum(window,'NOPAT'), capex=sum(window,'cash_capex'), cfo=sum(window,'cash_flow_from_operations');
      return {...r,capital,nopat,capex,cfo,da:sum(window,'depreciation_and_amortization'),roic:capital>0?nopat/capital:null,fcf:cfo-capex,absorption:capex/cfo};
    });
  }
  const companies=Object.fromEntries(Object.keys(D.financial).map(t=>[t,company(t)]));
  const aggregate=companies.MSFT.map(r=>{
    const group=['MSFT','GOOGL','AMZN','META'].map(t=>companies[t].find(x=>x.quarter===r.quarter));
    if(group.some(x=>!x||x.roic==null)) return null;
    const o={quarter:r.quarter,date:r.date};
    for(const k of ['capital','nopat','capex','cfo','fcf','da','cash_capex'])o[k]=sum(group,k);
    o.roic=o.nopat/o.capital;o.absorption=o.capex/o.cfo;return o;
  }).filter(Boolean);
  function chart(series,labels,yLabel,logScale=false) {
    const all=series.flatMap(s=>s.values.filter(Number.isFinite)); if(!all.length)return '<p>No matched observations.</p>';
    let low=Math.min(0,...all), high=Math.max(...all)*1.12;if(high===low)high=low+1;
    if(logScale){low=Math.log10(Math.min(...all)*.8);high=Math.log10(Math.max(...all)*1.12);}
    const X=i=>60+i*640/Math.max(1,labels.length-1), Y=v=>230-((logScale?Math.log10(v):v)-low)/(high-low)*200;
    let svg=`<svg viewBox="0 0 760 280" role="img" aria-label="${esc(yLabel)}"><text x="60" y="16">${esc(yLabel)}</text>`;
    for(let i=0;i<5;i++){const raw=low+(high-low)*i/4,v=logScale?10**raw:raw;svg+=`<line x1="60" x2="700" y1="${Y(v)}" y2="${Y(v)}" stroke="#d2cec3"/><text x="52" y="${Y(v)+4}" text-anchor="end">${num(v)}</text>`;}
    labels.forEach((l,i)=>{if(labels.length<10||i%3===0||i===labels.length-1)svg+=`<text x="${X(i)}" y="258" text-anchor="middle">${esc(l)}</text>`;});
    series.forEach(s=>{let path='',active=false;s.values.forEach((v,i)=>{if(v==null){active=false;return;}path+=`${active?'L':'M'}${X(i)},${Y(v)} `;active=true;});svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="3"/>`;s.values.forEach((v,i)=>{if(v!=null)svg+=`<circle cx="${X(i)}" cy="${Y(v)}" r="4" fill="${s.color}"><title>${esc(s.name)} · ${esc(labels[i])}: ${num(v)}</title></circle>`;});});
    return svg+'</svg><div class="research-legend">'+series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')+'</div>';
  }
  function table(headers,rows){return `<div class="research-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  function card(label,value,text){return `<article class="research-kpi"><span>${label}</span><strong>${value}</strong><p>${text}</p></article>`;}
  const last=D.months.filter(m=>m.complete).at(-1), prev=D.months.find(m=>m.month==='2026-07'), latest=aggregate.at(-1), prior=aggregate.find(x=>x.quarter==='2025Q2');
  host.innerHTML=`<div class="research-thesis"><span>THE CURRENT READ</span><h3>Usage is scaling. The financial payoff is lagging.</h3><p id="research-thesis-copy"></p></div>
    <div class="research-kpis">${card('OPENROUTER · AUG 2026',num(last.total/1e12)+'T',pct(change(last.total,prev.total))+' MoM; complete calendar months. Includes free and unattributed traffic.')}${card('CASH CAPEX · TTM JUN 2026','$'+num(latest.capex)+'B',pct(change(latest.capex,prior.capex))+' YoY across MSFT, GOOGL, AMZN and META.')}${card('CONSOLIDATED ROIC',pct(latest.roic),num((latest.roic-prior.roic)*100)+' pp YoY; aggregate NOPAT ÷ aggregate average capital.')}${card('CASH LEFT AFTER CAPEX','$'+num(latest.fcf)+'B',pct(change(latest.fcf,prior.fcf))+' YoY in the four-company TTM FCF proxy.')}</div>
    <div class="research-controls"><label>Financial universe <select id="research-company"><option value="ALL">Four-company matched aggregate</option>${Object.keys(companies).map(t=>`<option>${t}</option>`).join('')}</select></label><label>Investment leads token activity by <select id="research-lag"><option value="0">Same quarter</option><option value="1">1 quarter</option><option value="2">2 quarters</option></select></label></div>
    <div class="research-grid"><article class="research-card"><h3>Do demand and investment move together?</h3><p>Indexed levels on a logarithmic scale: equal vertical steps mean equal proportional changes. First fully covered matched quarter = 100. Cash CapEx is quarterly; NOPAT and ROIC use trailing four quarters.</p><div id="research-sync-chart"></div><div id="research-sync-copy" class="research-callout"></div></article><article class="research-card"><h3>Is profit keeping up with the capital base?</h3><p>Consolidated return, in percent. This includes mature businesses and non-AI investment.</p><div id="research-return-chart"></div><div id="research-return-copy" class="research-callout"></div></article></div>
    <article class="research-card"><h3>Matched-quarter evidence</h3><p>Missing-day quarters remain visible, but are excluded from the indexed chart and direction tests. Lag shifts financial observations earlier; it does not interpolate token history.</p><div id="research-quarter-table"></div><div id="research-statistics" class="research-callout"></div></article>
    <div class="research-grid"><article class="research-card"><h3>Demand momentum beyond the financial reporting window</h3><p>Average tokens per observed day, trillions. Gapped months are omitted; September is a partial window.</p><div id="research-month-chart"></div><p id="research-latest-copy" class="research-callout"></p></article><article class="research-card"><h3>Who is capturing the visible activity?</h3><label>Compare month <select id="research-month">${D.months.filter(m=>m.complete).map(m=>`<option value="${m.month}" ${m.month===last.month?'selected':''}>${m.month}</option>`).join('')}</select></label><div id="research-mix"></div><p>Author is the model namespace, not the inference host. Daily top-50 truncation leaves the long tail unattributed; author shares are lower bounds on total activity. They cannot be assigned to Azure, AWS or another hyperscaler’s revenue.</p></article></div>
    <article class="research-card"><h3>The price hurdle: volume growth is not revenue growth</h3><p>Illustrative scenario on the latest two complete months. Hold traffic coverage and mix constant, then vary realized revenue per token. This is not observed OpenRouter revenue.</p><label>Assumed change in revenue per token <input id="research-price" type="range" min="-90" max="20" step="1" value="-30"/><output id="research-price-value"></output></label><p id="research-price-copy" class="research-callout"></p></article>
    <div class="research-grid"><article class="research-card"><h3>What would strengthen the payback thesis?</h3><p>Token growth accompanied by stable realized pricing, cloud segment profit growth, and incremental cash covering incremental investment would connect activity to economics. Improving ROIC driven by NOPAT growth would be stronger evidence than a return uplift caused by capital reductions.</p></article><article class="research-card"><h3>What would weaken it?</h3><p>Usage rising while price per token falls faster, depreciation absorbs more operating profit, or cash CapEx keeps outrunning CFO would leave monetization unresolved. OpenRouter market-share gains could also explain rising activity without equivalent industry-wide demand growth.</p></article></div>
    <details class="research-card"><summary>Definitions, coverage and source audit</summary><p>Token data: ${D.rows.toLocaleString()} daily model records, January 1, 2025–${D.through}. Missing dates: ${D.missingDays.join(', ')}. Monthly totals reconcile to the workbook’s summary. September is never compared with a full month as a growth rate.</p><p>Source: <a href="https://openrouter.ai/rankings">OpenRouter (openrouter.ai/rankings)</a>, as of ${D.asOf}. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Aggregated and analyzed from Indexlist.xlsx, OpenRouter Token Value, columns A:D. <a href="https://openrouter.ai/docs/cookbook/administration/data-api">Dataset definitions</a>: prompt plus completion tokens, public traffic only, top 50 models plus other. Private and zero-data-retention traffic is excluded. Tokenizers and verbosity differ; token counts are neither spend nor unique users.</p><p>Financial inputs: Indexlist.xlsx, Hyperscaler Core Data Value, rows 4–17, company blocks B:L, M:W, X:AH, AI:AS and AT:BD. USD billions. Source cash outflows are sign-reversed. TTM = four quarterly observations. Core invested capital = equity + debt − cash and short-term investments; average = beginning and ending balances four quarters apart. Consolidated ROIC = TTM Bloomberg NOPAT ÷ average capital. Aggregate returns use summed numerator and denominator, not mean company percentages. Incremental ROIC = change in TTM NOPAT ÷ change in average capital over eight quarters; withheld if capital change ≤0 or &lt;5% of earlier capital.</p><p>Experimental definitions: all cash is deducted; long-term investments are unavailable; lease normalization is unresolved. These are not AI project returns. Oracle is shown separately through March 2026 because its calendarization is unresolved. Actual/estimate and release-date labels are absent from the source, so this is a cached research comparison, not a point-in-time backtest. Cash CapEx here differs from the legacy five-company total-investment series. No change to atmosphere scores.</p><p class="research-hash">Workbook SHA256: ${D.sha256}</p></details>`;
  document.getElementById('research-thesis-copy').textContent=`At the common June 2026 endpoint, four-company TTM cash investment grew ${pct(change(latest.capex,prior.capex))} YoY, while NOPAT grew ${pct(change(latest.nopat,prior.nopat))} and average invested capital grew ${pct(change(latest.capital,prior.capital))}. Consolidated ROIC fell ${num((prior.roic-latest.roic)*100)} percentage points. OpenRouter activity is rising sharply, but this sample does not yet connect that activity to equivalent corporate returns.`;
  function renderComparison(){
    const name=document.getElementById('research-company').value, lag=Number(document.getElementById('research-lag').value), financial=name==='ALL'?aggregate:companies[name].filter(x=>x.roic!=null);
    const matches=quarters.map(q=>{const y=Number(q.quarter.slice(0,4)),n=Number(q.quarter.at(-1))-1-lag, target=(y+Math.floor(n/4))+'Q'+((n%4+4)%4+1);return {q,f:financial.find(f=>f.quarter===target)};}).filter(x=>x.f);
    const full=matches.filter(x=>x.q.complete), base=full[0];
    document.getElementById('research-sync-chart').innerHTML=chart([{name:'OpenRouter tokens',color:'#1d7f80',values:matches.map(x=>x.q.complete?x.q.total/base.q.total*100:null)},{name:'Quarterly cash CapEx',color:'#d88952',values:matches.map(x=>x.q.complete?x.f.cash_capex/base.f.cash_capex*100:null)},{name:'TTM NOPAT',color:'#183b4a',values:matches.map(x=>x.q.complete?x.f.nopat/base.f.nopat*100:null)}],matches.map(x=>x.q.quarter),'Index · '+base.q.quarter+' = 100 · log scale',true);
    const end=full.at(-1), growth=change(end.q.total,base.q.total), cg=change(end.f.cash_capex,base.f.cash_capex);
    document.getElementById('research-sync-copy').textContent=`${base.q.quarter} → ${end.q.quarter}: token activity ${pct(growth)}, quarterly cash investment ${pct(cg)}. ${full.length} fully covered matched quarters. A shared upward trend alone cannot establish synchronization or capital productivity; the platform and corporate scopes differ.`;
    document.getElementById('research-return-chart').innerHTML=chart([{name:'Consolidated ROIC',color:'#183b4a',values:matches.map(x=>x.f.roic*100)}],matches.map(x=>x.f.quarter),'ROIC · %');
    const f=financial.at(-1), old=financial.find(x=>Number(x.quarter.slice(0,4))===Number(f.quarter.slice(0,4))-1&&x.quarter.at(-1)===f.quarter.at(-1)), eight=financial.find(x=>Number(x.quarter.slice(0,4))===Number(f.quarter.slice(0,4))-2&&x.quarter.at(-1)===f.quarter.at(-1));
    const inc=eight&&f.capital-eight.capital>0&&f.capital-eight.capital>=.05*eight.capital?(f.nopat-eight.nopat)/(f.capital-eight.capital):null;
    document.getElementById('research-return-copy').textContent=`Latest financial period ${f.quarter}: ROIC ${pct(f.roic)}; eight-quarter incremental ROIC ${pct(inc)}. Cash investment absorbs ${pct(f.absorption)} of CFO; cash CapEx / D&A is ${num(f.capex/f.da)}×. ${old?'Incremental CFO covers '+pct((f.cfo-old.cfo)/(f.capex-old.capex))+' of incremental CapEx; FCF proxy changes by $'+num(f.fcf-old.fcf)+'B YoY.':''} D&A is a lagging expense measure, not a maintenance-CapEx estimate. ${name==='ORCL'?'Oracle dates retain the workbook’s unresolved calendarization.':''}`;
    document.getElementById('research-quarter-table').innerHTML=table(['Token quarter','Coverage','Tokens (T)','Financial quarter','Cash CapEx ($B, Q)','NOPAT ($B, TTM)','ROIC'],matches.map(x=>[x.q.quarter,x.q.complete?'All days':x.q.days+' observed days · excluded',num(x.q.total/1e12),x.f.quarter,num(x.f.cash_capex),num(x.f.nopat),pct(x.f.roic)]));
    const pairs=[];
    for(let i=1;i<matches.length;i++){const a=matches[i-1],b=matches[i];if(a.q.complete&&b.q.complete)pairs.push([Math.log(b.q.total/a.q.total),Math.log(b.f.cash_capex/a.f.cash_capex)]);}
    const same=pairs.filter(([a,b])=>Math.sign(a)===Math.sign(b)).length;
    document.getElementById('research-statistics').textContent=`Direction check at this lag: ${same} of ${pairs.length} consecutive, fully covered quarterly changes move in the same direction. Correlation withheld: ${pairs.length} usable growth pairs, below the pre-set minimum of 8. This small, selected sample cannot identify a reliable lead/lag relationship. No interpolation, level correlation or annualized September estimate is used.`;
  }
  function renderMix(){const m=D.months.find(x=>x.month===document.getElementById('research-month').value),i=D.months.indexOf(m),p=D.months[i-1];const top=Object.entries(m.authors).filter(([k])=>k!=='other').sort((a,b)=>b[1]-a[1]).slice(0,6);document.getElementById('research-mix').innerHTML=table(['Model author','Total-traffic share','Change vs prior month'],top.map(([a,t])=>[esc(a),pct(t/m.total),p?.complete?num((t/m.total-(p.authors[a]||0)/p.total)*100)+' pp':'—']))+`<p class="research-callout">Explicit :free variants: ${pct(m.free/m.total)} of all tokens. Unattributed “other”: ${pct(m.other/m.total)}. The free share is a lower bound; the remainder is not verified paid usage. Share changes can reflect movement into or out of the daily top 50.</p>`;}
  function renderPrice(){const rate=Number(document.getElementById('research-price').value)/100,g=last.total/prev.total;document.getElementById('research-price-value').textContent=pct(rate);document.getElementById('research-price-copy').textContent=`August volume grew ${pct(g-1)}. With revenue per token changing ${pct(rate)}, implied revenue changes ${pct(g*(1+rate)-1)}. A ${pct(1-1/g)} price decline exactly offsets that volume growth. Real pricing, discounts, free usage and model mix are missing, so this is a sensitivity, not a revenue estimate.`;}
  document.getElementById('research-month-chart').innerHTML=chart([{name:'Complete-month daily average',color:'#1d7f80',values:D.months.map(m=>m.complete?m.total/m.days/1e12:null)},{name:'September 1–9 only',color:'#d88952',values:D.months.map(m=>m.month==='2026-09'?m.total/m.days/1e12:null)}],D.months.map(m=>m.month),'Trillion tokens / observed day');
  const partial=D.months.at(-1);document.getElementById('research-latest-copy').textContent=`August averaged ${num(last.total/last.days/1e12)}T tokens/day; September 1–9 averaged ${num(partial.total/partial.days/1e12)}T. The partial window may reflect weekday mix or releases and is not a full-month growth comparison. July–September activity has no matching reported financial quarter in this workbook.`;
  document.getElementById('research-company').addEventListener('change',renderComparison);document.getElementById('research-lag').addEventListener('change',renderComparison);document.getElementById('research-month').addEventListener('change',renderMix);document.getElementById('research-price').addEventListener('input',renderPrice);
  renderComparison();renderMix();renderPrice();
})();
