#!/usr/bin/env python3
"""Generate the Frontier Labs web snapshot from AI company revenue reports."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


DATA_ROOT = Path("/Users/linyu/Library/CloudStorage/OneDrive-Personal/AI_INDEX")
SOURCE = DATA_ROOT / "ai_companies" / "ai_companies_revenue_reports.csv"
OUTPUT = Path(__file__).resolve().parents[1] / "app" / "frontier-labs-snapshot.ts"
LABS = ["OpenAI", "Anthropic"]


def money_label(value: float, floor: bool = False) -> str:
    amount = value / 1_000_000_000
    formatted = f"{amount:.1f}".rstrip("0").rstrip(".")
    return f"{'>' if floor else ''}${formatted}B"


def main() -> None:
    data = pd.read_csv(SOURCE)
    data["Date"] = pd.to_datetime(data["Date"])
    data["Report date"] = pd.to_datetime(data["Report date"])
    payload = {"metadata": {"source": "ai_companies_revenue_reports.csv", "asOf": str(data["Report date"].max().date())}, "labs": {}}

    for lab in LABS:
        rows = data[(data["Company"] == lab) & (data["Scope"] == "Full company")].copy()
        annualized = rows[
            rows["Annualized revenue type"].isin(["Annualized run rate", "Annual recurring revenue (ARR)"])
            & rows["Annualized revenue (USD)"].notna()
            & (rows["Date"] >= pd.Timestamp("2024-12-01"))
        ].sort_values("Date")
        latest = annualized.iloc[-1]
        end_2025 = annualized[annualized["Date"] == pd.Timestamp("2025-12-31")].sort_values("Annualized revenue (USD)").iloc[-1]
        fy_2025 = rows[(rows["Date"] == pd.Timestamp("2025-12-31")) & (rows["Period type"] == "Year")].iloc[-1]
        latest_value = float(latest["Annualized revenue (USD)"])
        end_value = float(end_2025["Annualized revenue (USD)"])
        floor = lab == "OpenAI"
        payload["labs"][lab] = {
            "latest": money_label(latest_value, floor),
            "latestValue": latest_value / 1_000_000_000,
            "latestDate": latest["Date"].strftime("%d %b %Y"),
            "latestType": latest["Annualized revenue type"],
            "latestConfidence": latest["Confidence"],
            "fy2025Revenue": money_label(float(fy_2025["Period revenue"])),
            "end2025RunRate": money_label(end_value),
            "growthFromEnd2025": round((latest_value / end_value - 1) * 100, 1),
            "series": [
                {
                    "date": row["Date"].strftime("%Y-%m-%d"),
                    "label": row["Date"].strftime("%b-%y"),
                    "value": round(float(row["Annualized revenue (USD)"]) / 1_000_000_000, 3),
                    "type": row["Annualized revenue type"],
                    "confidence": row["Confidence"],
                }
                for _, row in annualized.iterrows()
            ],
        }

    content = "// Generated by scripts/build-frontier-labs-snapshot.py. Do not edit manually.\n"
    content += "export const frontierLabsSnapshot = " + json.dumps(payload, indent=2) + " as const;\n"
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
