"""Build auditable chain totals without summing different source currencies."""
import datetime,hashlib,json,re
from pathlib import Path
import openpyxl
root=Path(__file__).resolve().parents[1]
source=Path('/Users/linyu/Library/CloudStorage/OneDrive-Personal/AI_Index/Indexlist.xlsx')
text=(root/'app/credit-financial-history.ts').read_text()
financial=json.loads(text[text.index('{'):text.rindex('}')+1])
w=openpyxl.load_workbook(source,read_only=True,data_only=False)
formula=w['Supply Chain Financial Formula']['C3'].value
formula=getattr(formula,'text',str(formula))
# The current query spells this Currncy=USD, which does not establish conversion.
usd_query=bool(re.search(r'(?i)["\'](?:currency|curncy)=USD["\']',formula))
native={'ASML':'EUR','2330':'TWD','000660':'KRW','005930':'KRW','8035':'JPY'}
companies={t:{'currency':'USD' if usd_query else native.get(t,'USD'),'periods':[{'period':r['period'],'revenue':r.get('ttmRevenue'),'ebitda':r.get('ttmEbitda'),'sourceRange':r['sourceRange']} for r in rows]} for t,rows in financial['history'].items()}
periods=sorted({p['period'] for c in companies.values() for p in c['periods']})
complete=[p for p in periods if all(any(r['period']==p and r['revenue'] is not None and r['ebitda'] is not None for r in c['periods']) for c in companies.values())]
result={'metadata':{'source':'Indexlist.xlsx','sheet':'Supply Chain Financial Value','sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'extractedAt':str(datetime.date.today()),'coverage':len(companies),'latestCommonPeriod':complete[-1] if complete else None,'usdQuery':usd_query,'currencyMethod':'Source BQL explicitly requests USD' if usd_query else 'Reporting-currency groups: USD except ASML EUR, TSMC TWD, SK hynix/Samsung KRW and Tokyo Electron JPY. The current Currncy=USD parameter does not verify conversion. Global revenue/EBITDA shares are withheld.','periodMethod':'Four consecutive source calendar quarters, without annualizing a single quarter. Same TTM end date for all eligible issuers. Missing amounts remain null.','shareMethod':'Company amount / sum of available same-currency company amounts at the selected TTM date. EBITDA totals retain negative contributions. This is covered-company financial scale, not AI-only revenue, value added, supplier payments or market share.'},'periods':periods,'companies':companies}
(root/'app/chain-economics-snapshot.ts').write_text('// Generated by scripts/build-chain-economics.py\nexport const chainEconomicsSnapshot = '+json.dumps(result,separators=(',',':'))+' as const;\n')
print(json.dumps(result['metadata'],indent=2))
