"""Refresh market and financial observations from cached workbook values."""
import datetime, hashlib, json, math, calendar
from pathlib import Path
import openpyxl
root=Path(__file__).resolve().parents[1]
source=Path('/Users/linyu/Library/CloudStorage/OneDrive-Personal/AI_Index/Indexlist.xlsx')
w=openpyxl.load_workbook(source,read_only=True,data_only=True)
stock=list(w['Supply Chain Stock Value'].values)
financial=json.loads((root/'app/value-chain-financials.ts').read_text().split(' = ',1)[1].rsplit(' as const;',1)[0])['companies']
def clean(v):return float(v) if isinstance(v,(int,float)) and math.isfinite(v) else None
def shifted(d,n):
 m=d.month-n;y=d.year
 while m<1:m+=12;y-=1
 return d.replace(year=y,month=m,day=min(d.day,calendar.monthrange(y,m)[1]))
companies={}; curves={}; inferred_opening_caps=[]
for col,id in enumerate(stock[0][1:],1):
 if not isinstance(id,str) or not id.strip():continue
 if 'return_series' not in str(stock[1][col]):continue
 ticker=id.strip().split()[0]
 cap_col=next((i for i in range(col+1,min(col+2,len(stock[0]))) if 'cur_mkt_cap' in str(stock[1][i])),None)
 obs=[(r[0].date(),clean(r[col])) for r in stock[2:] if isinstance(r[0],datetime.datetime)]
 cap_obs=[(r[0].date(),clean(r[cap_col])) for r in stock[2:] if isinstance(r[0],datetime.datetime)] if cap_col is not None else []
 valid_caps=[(d,v) for d,v in cap_obs if v is not None and v>0]
 valid=[(d,v) for d,v in obs if v is not None]; end,last=valid[-1]
 def compounded(start):
  vals=[v for d,v in valid if start<d<=end]; total=1
  for v in vals:total*=1+v
  return (total-1)*100 if vals else None
 f=financial[ticker];currency={'2330':'TWD','000660':'KRW','005930':'KRW','8035':'JPY'}.get(ticker,'USD')
 baseline=datetime.date(2025,12,31)
 opening=next((v for d,v in valid_caps if d==baseline),None)
 opening_estimated=False
 if opening is None and valid_caps:
  first_date,first_cap=valid_caps[0]
  opening_returns=[v for d,v in valid if baseline<d<=first_date]
  growth=math.prod(1+v for v in opening_returns)
  if growth>0:
   opening=first_cap/growth;opening_estimated=True;inferred_opening_caps.append(ticker)
 cap_end,cap_last=valid_caps[-1] if valid_caps else (None,None)
 companies[ticker]={'ticker':ticker,'price':None,'currency':currency,'change1d':last*100,'change1m':compounded(shifted(end,1)),'change3m':compounded(shifted(end,3)),'changeYtd':compounded(baseline),'asOf':str(end),'marketCap':cap_last,'marketCapAsOf':str(cap_end) if cap_end else None,'openingMarketCap':opening,'openingMarketCapEstimated':opening_estimated,'revenueGrowthYoy':f['revenueGrowth'],'capexGrowthYoy':f['capexGrowth'],'financialAsOf':f['period'],'fundamentalComposite':None}
 total=1;curve=[]
 for d,v in obs:
  if v is not None:total*=1+v
  if v is not None and v<=-1:raise ValueError(f'Invalid return for {ticker}: {d}')
  cap=dict(cap_obs).get(d)
  curve.append({'date':str(d),'dailyReturn':None if v is None else v*100,'cumulativeReturn':None if v is None else (total-1)*100,'marketCap':cap if cap is not None and cap>0 else None})
 curves[ticker]=curve
payload={'metadata':{'source':'Indexlist.xlsx','sheet':'Supply Chain Stock Value','financialSheet':'Supply Chain Financial Value','sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'baseline':'2025-12-31','coverage':len(companies),'asOf':max(r['asOf'] for r in companies.values()),'marketCapCurrency':'USD','marketCapCoverage':sum(r['marketCap'] is not None for r in companies.values()),'inferredOpeningCaps':inferred_opening_caps,'returnStarts':{t:next(r['date'] for r in rows if r['dailyReturn'] is not None) for t,rows in curves.items()},'openingCapMethod':'Missing 31 December caps use first observed USD cap divided by available compounded local returns to that date as an opening proxy. If no return precedes that cap, the first cap is used unchanged. This does not recover missing opening-session returns. Later weights use observed lagged USD caps.','q2FinancialCoverage':sum(r['period'][5:7]=='06' for r in financial.values()),'q1FinancialFallback':sum(r['period'][5:7]=='03' for r in financial.values()),'method':'Compound observed daily decimal returns: product(1 + return) - 1. Missing source values remain null. Market caps are USD per the source BQL Currency=USD parameter. Returns remain local-listing returns, not FX-translated USD returns. Dividend adjustment follows Bloomberg return_series and is not independently verified.'},'companies':companies,'series':curves}
(root/'app/supply-chain-stock-snapshot.ts').write_text('// Generated by scripts/build-supply-chain-stock.py\nexport const supplyChainStockSnapshot = '+json.dumps(payload,separators=(',',':'))+' as const;\n')
print(f'Refreshed {len(companies)} companies through {payload["metadata"]["asOf"]}')
